MODULE BC_MODULE
  USE CONFIG_MODULE
  USE GRID_MODULE
  USE VARIABLE_MODULE
  USE EOS_MODULE
  USE PROP_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_BC
  
  TYPE, EXTENDS(T_BCINFO) :: T_BCINFO_P
    PROCEDURE(P_BCTYPE), POINTER :: BCTYPE
    CHARACTER(4) :: FACE
  END TYPE T_BCINFO_P
  
  TYPE T_REF
    REAL(8), DIMENSION(:), ALLOCATABLE :: PV,TV,DV
  END TYPE T_REF
  
  TYPE T_BC
    PRIVATE
    INTEGER :: RANK,SIZE,NBC,NCON
    INTEGER :: ITURB
    INTEGER :: NPV,NTV,NDV,NGRD
    TYPE(T_REF) :: REF
    TYPE(T_BCINFO_P), DIMENSION(:), ALLOCATABLE :: BCINFO
    TYPE(T_CONNECTINFO), DIMENSION(:), ALLOCATABLE ::CONNECTINFO
    CONTAINS
      PROCEDURE :: CONSTRUCT
      PROCEDURE :: DESTRUCT
      PROCEDURE :: SETBC
      PROCEDURE, PRIVATE :: BCCORNER
  END TYPE T_BC

  INTERFACE
    SUBROUTINE P_BCTYPE(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPORT T_BCINFO_P
      IMPORT T_REF
      IMPORT T_GRID
      IMPORT T_VARIABLE
      IMPORT T_EOS
      IMPORT T_PROP  
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
    END SUBROUTINE P_BCTYPE
  END INTERFACE
  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CONSTRUCT(BC,CONFIG,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BC), INTENT(OUT) :: BC
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(IN) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: L,N,M
      INTEGER, PARAMETER :: DIM = 2
      
      BC%RANK = CONFIG%GETRANK() 
      BC%SIZE = CONFIG%GETSIZE()
      BC%ITURB = CONFIG%GETITURB()

      BC%NBC = GRID%GETNBC()
      BC%NCON = GRID%GETNCON()
      BC%NPV = VARIABLE%GETNPV()
      BC%NTV = VARIABLE%GETNTV()
      BC%NDV = VARIABLE%GETNDV()
      BC%NGRD = GRID%GETNGRD()

      ALLOCATE(BC%REF%PV(BC%NPV),BC%REF%DV(BC%NDV),BC%REF%TV(BC%NTV))
      
      BC%REF%PV(1) = CONFIG%GETPREF()
      BC%REF%PV(2) = CONFIG%GETUREF()*DCOS(CONFIG%GETAOA())
      BC%REF%PV(3) = CONFIG%GETUREF()*DSIN(CONFIG%GETAOA())
      BC%REF%PV(4) = CONFIG%GETTREF()
      BC%REF%PV(5) = CONFIG%GETY1REF()
      BC%REF%PV(6) = CONFIG%GETY2REF()
      
      CALL EOS%DETEOS(BC%REF%PV(1),BC%REF%PV(4),BC%REF%PV(5),BC%REF%PV(6),BC%REF%DV)
      
      IF(BC%ITURB.GE.-2) THEN
        CALL PROP%DETPROP(BC%REF%DV(3),BC%REF%DV(4),BC%REF%DV(5),BC%REF%PV(4),BC%REF%PV(5),BC%REF%PV(6),BC%REF%TV(1:2))
        IF(BC%ITURB.GE.-1) THEN
          BC%REF%TV(3) = CONFIG%GETEMUTREF()
          BC%REF%PV(7) = CONFIG%GETKREF()
          BC%REF%PV(8) = CONFIG%GETOREF()
        END IF
      END IF
 
      ALLOCATE(BC%BCINFO(BC%NBC),BC%CONNECTINFO(BC%NCON))
      
      DO N=1,BC%NBC
        BC%BCINFO(N)%BCNAME = GRID%GETBCNAME(N)
        DO M=1,DIM
          BC%BCINFO(N)%ISTART(M) = GRID%GETBCISTART(N,M)
          BC%BCINFO(N)%IEND(M)   = GRID%GETBCIEND(N,M)
        END DO
        
        IF(BC%BCINFO(N)%ISTART(2).EQ.BC%BCINFO(N)%IEND(2)) THEN
          IF(BC%BCINFO(N)%ISTART(2).EQ.1) THEN
            BC%BCINFO(N)%FACE = 'JMIN'
            BC%BCINFO(N)%ISTART(2) = BC%BCINFO(N)%ISTART(2)-2
          ELSE
            BC%BCINFO(N)%FACE = 'JMAX'
            BC%BCINFO(N)%IEND(2) = BC%BCINFO(N)%IEND(2)+2
          END IF
        ELSE IF(BC%BCINFO(N)%ISTART(1).EQ.BC%BCINFO(N)%IEND(1)) THEN
          IF(BC%BCINFO(N)%ISTART(1).EQ.1) THEN
            BC%BCINFO(N)%FACE = 'IMIN'
            BC%BCINFO(N)%ISTART(1) = BC%BCINFO(N)%ISTART(1)-2
          ELSE
            BC%BCINFO(N)%FACE = 'IMAX'
            BC%BCINFO(N)%IEND(1) = BC%BCINFO(N)%IEND(1)+2
          END IF 
        END IF
        
        IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCWallInviscid') THEN
          BC%BCINFO(N)%BCTYPE => BCWALLINVISCID
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCWallViscous') THEN
          SELECT CASE(BC%ITURB)
          CASE(-1)
            BC%BCINFO(N)%BCTYPE => BCWALLVISCOUSKE
          CASE(0)
            BC%BCINFO(N)%BCTYPE => BCWALLVISCOUSKW
          CASE DEFAULT
            BC%BCINFO(N)%BCTYPE => BCWALLVISCOUS
          END SELECT
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCInflow') THEN
          BC%BCINFO(N)%BCTYPE => BCINFLOW
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCInflowSubsonic') THEN
          BC%BCINFO(N)%BCTYPE => BCINFLOWSUBSONIC
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCInflowSupersonic') THEN
          BC%BCINFO(N)%BCTYPE => BCINFLOWSUPERSONIC
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCOutflow') THEN
          BC%BCINFO(N)%BCTYPE => BCOUTFLOW
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCOutflowSubsonic') THEN
          BC%BCINFO(N)%BCTYPE => BCOUTFLOWSUBSONIC
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCOutflowSupersonic') THEN
          BC%BCINFO(N)%BCTYPE => BCOUTFLOWSUPERSONIC
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCFarfield') THEN
          BC%BCINFO(N)%BCTYPE => BCFARFIELD
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCDegeneratePoint') THEN
          BC%BCINFO(N)%BCTYPE => BCDEGENERATEPOINT
        ELSE IF(TRIM(BC%BCINFO(N)%BCNAME).EQ.'BCSymmetryPlane') THEN
          BC%BCINFO(N)%BCTYPE => BCSYMMETRYPLANE
        ELSE
          BC%BCINFO(N)%BCTYPE => NULL()
          WRITE(*,*) 'ERROR, CHECK BC NAME'
          STOP
        END IF
      END DO

      DO N=1,BC%NCON
        BC%CONNECTINFO(N)%DONOR = GRID%GETCONNECTDONOR(N)
        
        DO M=1,DIM
          BC%CONNECTINFO(N)%ISTART(M) = GRID%GETCONNECTISTART(N,M)
          BC%CONNECTINFO(N)%IEND(M)   = GRID%GETCONNECTIEND(N,M)
          BC%CONNECTINFO(N)%ISTART_DONOR(M) = GRID%GETCONNECTISTART_DONOR(N,M)
          BC%CONNECTINFO(N)%IEND_DONOR(M)   = GRID%GETCONNECTIEND_DONOR(N,M)
          DO L=1,DIM
            BC%CONNECTINFO(N)%TRANSMAT(M,L) = GRID%GETCONNECTTRANSMAT(N,M,L)
          END DO
        END DO
        
        IF(BC%CONNECTINFO(N)%ISTART(2).EQ.BC%CONNECTINFO(N)%IEND(2)) THEN
          IF(BC%CONNECTINFO(N)%ISTART(2).EQ.2) THEN
            BC%CONNECTINFO(N)%IEND(2) = BC%CONNECTINFO(N)%IEND(2) + 2
          ELSE
            BC%CONNECTINFO(N)%ISTART(2) = BC%CONNECTINFO(N)%ISTART(2) - 2
          END IF
        ELSE IF(BC%CONNECTINFO(N)%ISTART(1).EQ.BC%CONNECTINFO(N)%IEND(1)) THEN
          IF(BC%CONNECTINFO(N)%ISTART(1).EQ.2) THEN
            BC%CONNECTINFO(N)%IEND(1) = BC%CONNECTINFO(N)%IEND(1) + 2
          ELSE
            BC%CONNECTINFO(N)%ISTART(1) = BC%CONNECTINFO(N)%ISTART(1) - 2
          END IF
        END IF

        IF(BC%CONNECTINFO(N)%ISTART_DONOR(2).EQ.BC%CONNECTINFO(N)%IEND_DONOR(2)) THEN
          DO M=1,DIM
            IF(BC%CONNECTINFO(N)%TRANSMAT(M,2).EQ.-1) THEN
              BC%CONNECTINFO(N)%TRANSMAT(M,2) = 1
            END IF
          END DO
          IF(BC%CONNECTINFO(N)%ISTART_DONOR(2).EQ.1) THEN
            BC%CONNECTINFO(N)%ISTART_DONOR(2) = BC%CONNECTINFO(N)%ISTART_DONOR(2) - 2
          ELSE
            BC%CONNECTINFO(N)%IEND_DONOR(2) = BC%CONNECTINFO(N)%IEND_DONOR(2) + 2
          END IF
        ELSE IF(BC%CONNECTINFO(N)%ISTART_DONOR(1).EQ.BC%CONNECTINFO(N)%IEND_DONOR(1)) THEN
          DO M=1,DIM
            IF(BC%CONNECTINFO(N)%TRANSMAT(M,1).EQ.-1) THEN
              BC%CONNECTINFO(N)%TRANSMAT(M,1) = 1
            END IF
          END DO
          IF(BC%CONNECTINFO(N)%ISTART_DONOR(1).EQ.1) THEN
            BC%CONNECTINFO(N)%ISTART_DONOR(1) = BC%CONNECTINFO(N)%ISTART_DONOR(1) - 2
          ELSE
            BC%CONNECTINFO(N)%IEND_DONOR(1) = BC%CONNECTINFO(N)%IEND_DONOR(1) + 2
          END IF
        END IF
      END DO
      
    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE DESTRUCT(BC)
      IMPLICIT NONE
      CLASS(T_BC), INTENT(INOUT) :: BC
      INTEGER :: N
      
      DO N=1,BC%NBC
        IF(ASSOCIATED(BC%BCINFO(N)%BCTYPE)) NULLIFY(BC%BCINFO(N)%BCTYPE)
      END DO
      
      DEALLOCATE(BC%REF%PV,BC%REF%DV,BC%REF%TV)
      DEALLOCATE(BC%BCINFO,BC%CONNECTINFO)
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETBC(BC,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      INCLUDE 'mpif.h'
      CLASS(T_BC), INTENT(IN) :: BC
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,N,M,L
      INTEGER :: IS,IE,JS,JE,II,JJ
      INTEGER :: NUM
      INTEGER :: IER,REQUEST1,REQUEST2
      INTEGER :: STATUS(MPI_STATUS_SIZE)
      REAL(8) :: PV(BC%NPV),DV(BC%NDV),TV(BC%NTV)
      REAL(8), DIMENSION(:), ALLOCATABLE :: SENDBUF,RECVBUF
      
      
      DO N=1,BC%NBC
        CALL BC%BCINFO(N)%BCTYPE(BC%REF,GRID,VARIABLE,EOS,PROP)
      END DO
      
      DO N=1,BC%NCON
        NUM = (BC%NPV+BC%NTV+BC%NDV)*(ABS(BC%CONNECTINFO(N)%ISTART(2)-BC%CONNECTINFO(N)%IEND(2))+1)*(ABS(BC%CONNECTINFO(N)%ISTART(1)-BC%CONNECTINFO(N)%IEND(1))+1)
        ALLOCATE(SENDBUF(NUM),RECVBUF(NUM))

        L = 0
        DO J=BC%CONNECTINFO(N)%ISTART(2),BC%CONNECTINFO(N)%IEND(2)
          DO I=BC%CONNECTINFO(N)%ISTART(1),BC%CONNECTINFO(N)%IEND(1)
            PV = VARIABLE%GETPV(I,J)
            TV = VARIABLE%GETTV(I,J)
            DV = VARIABLE%GETDV(I,J)
            DO M=1,BC%NPV
              L = L + 1
              SENDBUF(L) = PV(M)
            END DO
            DO M=1,BC%NTV
              L = L + 1
              SENDBUF(L) = TV(M)
            END DO
            DO M=1,BC%NDV
              L = L + 1
              SENDBUF(L) = DV(M)
            END DO            
          END DO
        END DO
          
        IF(BC%RANK.NE.BC%CONNECTINFO(N)%DONOR) THEN 
      
          CALL MPI_ISEND(SENDBUF,NUM,MPI_REAL8,BC%CONNECTINFO(N)%DONOR,BC%RANK,MPI_COMM_WORLD,REQUEST1,IER)
          CALL MPI_IRECV(RECVBUF,NUM,MPI_REAL8,BC%CONNECTINFO(N)%DONOR,BC%CONNECTINFO(N)%DONOR,MPI_COMM_WORLD,REQUEST2,IER)
          CALL MPI_WAIT(REQUEST1,STATUS,IER)
          CALL MPI_WAIT(REQUEST2,STATUS,IER)
          
          IS = BC%CONNECTINFO(N)%ISTART_DONOR(1)
          IE = BC%CONNECTINFO(N)%IEND_DONOR(1)
          JS = BC%CONNECTINFO(N)%ISTART_DONOR(2)
          JE = BC%CONNECTINFO(N)%IEND_DONOR(2)
      
          IF(BC%CONNECTINFO(N)%ISTART_DONOR(2).GT.BC%CONNECTINFO(N)%IEND_DONOR(2)) THEN
            JS = BC%CONNECTINFO(N)%IEND_DONOR(2)
            JE = BC%CONNECTINFO(N)%ISTART_DONOR(2)
          END IF
          
          IF(BC%CONNECTINFO(N)%ISTART_DONOR(1).GT.BC%CONNECTINFO(N)%IEND_DONOR(1)) THEN
            IS = BC%CONNECTINFO(N)%IEND_DONOR(1)
            IE = BC%CONNECTINFO(N)%ISTART_DONOR(1)       
          END IF         
          
          L = 0
          DO J=JS,JE
            DO I=IS,IE
              II = BC%CONNECTINFO(N)%TRANSMAT(1,1)*(I-BC%CONNECTINFO(N)%ISTART_DONOR(1))+BC%CONNECTINFO(N)%TRANSMAT(2,1)*(J-BC%CONNECTINFO(N)%ISTART_DONOR(2))+BC%CONNECTINFO(N)%ISTART(1)
              JJ = BC%CONNECTINFO(N)%TRANSMAT(1,2)*(I-BC%CONNECTINFO(N)%ISTART_DONOR(1))+BC%CONNECTINFO(N)%TRANSMAT(2,2)*(J-BC%CONNECTINFO(N)%ISTART_DONOR(2))+BC%CONNECTINFO(N)%ISTART(2)
              DO M=1,BC%NPV
                L = L + 1
                CALL VARIABLE%SETPV(M,II,JJ,RECVBUF(L))
              END DO
              DO M=1,BC%NTV
                L = L + 1
                CALL VARIABLE%SETTV(M,II,JJ,RECVBUF(L))
              END DO
              DO M=1,BC%NDV
                L = L + 1
                CALL VARIABLE%SETDV(M,II,JJ,RECVBUF(L))
              END DO
            END DO
          END DO
        ELSE ! NO MPI BOUNDARY
          
          RECVBUF = SENDBUF
          
          L = 0
          DO J=BC%CONNECTINFO(N)%ISTART(2),BC%CONNECTINFO(N)%IEND(2)
            DO I=BC%CONNECTINFO(N)%ISTART(1),BC%CONNECTINFO(N)%IEND(1)
              II = BC%CONNECTINFO(N)%TRANSMAT(1,1)*(I-BC%CONNECTINFO(N)%ISTART(1))+BC%CONNECTINFO(N)%TRANSMAT(1,2)*(J-BC%CONNECTINFO(N)%ISTART(2))+BC%CONNECTINFO(N)%ISTART_DONOR(1)
              JJ = BC%CONNECTINFO(N)%TRANSMAT(2,1)*(I-BC%CONNECTINFO(N)%ISTART(1))+BC%CONNECTINFO(N)%TRANSMAT(2,2)*(J-BC%CONNECTINFO(N)%ISTART(2))+BC%CONNECTINFO(N)%ISTART_DONOR(2)
              DO M=1,BC%NPV
                L = L + 1
                CALL VARIABLE%SETPV(M,II,JJ,RECVBUF(L))
              END DO
              DO M=1,BC%NTV
                L = L + 1
                CALL VARIABLE%SETTV(M,II,JJ,RECVBUF(L))
              END DO
              DO M=1,BC%NDV
                L = L + 1
                CALL VARIABLE%SETDV(M,II,JJ,RECVBUF(L))
              END DO
            END DO
          END DO
          
        END IF
        DEALLOCATE(SENDBUF,RECVBUF)
      END DO
      
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,2,2,-1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,1,2,-1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,2,1,-1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,1,1,-1,-1)
      
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX(),2,1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX()+1,2,1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX(),1,1,-1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX()+1,1,1,-1)
      
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,2,GRID%GETJMAX(),-1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,1,GRID%GETJMAX(),-1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,2,GRID%GETJMAX()+1,-1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,1,GRID%GETJMAX()+1,-1,1)
      
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX(),GRID%GETJMAX(),1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX()+1,GRID%GETJMAX(),1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX(),GRID%GETJMAX()+1,1,1)
      CALL BC%BCCORNER(GRID,VARIABLE,EOS,PROP,GRID%GETIMAX()+1,GRID%GETJMAX()+1,1,1)
      
    END SUBROUTINE SETBC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCCORNER(BC,GRID,VARIABLE,EOS,PROP,I,J,II,JJ)
      IMPLICIT NONE
      CLASS(T_BC), INTENT(IN) :: BC
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER, INTENT(IN) :: I,J,II,JJ
      INTEGER :: N
      REAL(8) :: DQDX(BC%NPV),DQDY(BC%NPV),PV(BC%NPV)
      REAL(8) :: DV(BC%NDV),TV(BC%NTV)
      
      DQDX = 0.5D0*(VARIABLE%GETPV(I+II,J)-VARIABLE%GETPV(I,J))
      DQDY = 0.5D0*(VARIABLE%GETPV(I,J+JJ)-VARIABLE%GETPV(I,J))
      PV = VARIABLE%GETPV(I,J)+DQDX+DQDY
      
      DO N=1,BC%NPV
        CALL VARIABLE%SETPV(N,I+II,J+JJ,PV(N))
      END DO
      
      CALL EOS%DETEOS(PV(1)+BC%REF%PV(1),PV(4),PV(5),PV(6),DV)
      
      DO N=1,BC%NDV
        CALL VARIABLE%SETDV(N,I+II,J+JJ,DV(N))
      END DO
      
      IF(BC%ITURB.NE.-3) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
      
      DO N=1,BC%NTV
        CALL VARIABLE%SETTV(N,I+II,J+JJ,TV(N))
      END DO
      

    END SUBROUTINE BCCORNER
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCWALLINVISCID(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      REAL(8) :: NX(2),VAR
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETCX(BCINFO%IEND(1),J)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETCX(BCINFO%ISTART(1)-1,J)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETEX(I,BCINFO%IEND(2))
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETEX(I,BCINFO%ISTART(2)-1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
    
    END SUBROUTINE BCWALLINVISCID
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCWALLVISCOUS(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCWALLVISCOUS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCWALLVISCOUSKE(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7,8)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7,8)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7,8)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7,8)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCWALLVISCOUSKE
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCWALLVISCOUSKW(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV()),GRD(GRID%GETNGRD())
      REAL(8) :: X(2),X1(2),VAR,XCC,YCC
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE(8)
                X = GRID%GETX(BCINFO%IEND(1)+1,J)
                X1 = GRID%GETX(BCINFO%IEND(1)+1,J+1)
                GRD = GRID%GETGRD(BCINFO%IEND(1)+1,J)
                XCC = 0.5D0*(X(1)+X1(1))
                YCC = 0.5D0*(X(2)+X1(2))
                VAR = 1600.D0*TV(1)/DV(1)/((GRD(2)-XCC)**2+(GRD(3)-YCC)**2)-PV(M)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE(8)
                X = GRID%GETX(BCINFO%ISTART(1),J)
                X1 = GRID%GETX(BCINFO%ISTART(1),J+1)
                GRD = GRID%GETGRD(BCINFO%ISTART(1)-1,J)
                XCC = 0.5D0*(X(1)+X1(1))
                YCC = 0.5D0*(X(2)+X1(2))
                VAR = 1600.D0*TV(1)/DV(1)/((GRD(2)-XCC)**2+(GRD(3)-YCC)**2)-PV(M)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE(8)
                X = GRID%GETX(I,BCINFO%IEND(2)+1)
                X1 = GRID%GETX(I+1,BCINFO%IEND(2)+1)
                GRD = GRID%GETGRD(I,BCINFO%IEND(2)+1)
                XCC = 0.5D0*(X(1)+X1(1))
                YCC = 0.5D0*(X(2)+X1(2))
                VAR = 1600.D0*TV(1)/DV(1)/((GRD(2)-XCC)**2+(GRD(3)-YCC)**2)-PV(M)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2,3,7)
                CALL VARIABLE%SETPV(M,I,J,-PV(M))
              CASE(8)
                X = GRID%GETX(I,BCINFO%ISTART(2))
                X1 = GRID%GETX(I+1,BCINFO%ISTART(2))
                GRD = GRID%GETGRD(I,BCINFO%ISTART(2)-1)
                XCC = 0.5D0*(X(1)+X1(1))
                YCC = 0.5D0*(X(2)+X1(2))
                VAR = 1600.D0*TV(1)/DV(1)/((GRD(2)-XCC)**2+(GRD(3)-YCC)**2)-PV(M)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,-TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              END SELECT
            END DO
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCWALLVISCOUSKW
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCINFLOW(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCINFLOW
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCINFLOWSUBSONIC(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            CALL VARIABLE%SETPV(1,I,J,PV(1))
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            CALL VARIABLE%SETPV(1,I,J,PV(1))
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            CALL VARIABLE%SETPV(1,I,J,PV(1))
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            CALL VARIABLE%SETPV(1,I,J,PV(1))
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCINFLOWSUBSONIC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCINFLOWSUPERSONIC(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      REAL(8) :: TV(VARIABLE%GETNTV())
      INTEGER :: I,J,M
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
              END SELECT
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1) 
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              SELECT CASE(M)
              CASE(3)
                CALL VARIABLE%SETTV(M,I,J,TV(M))
              CASE DEFAULT
                CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
              END SELECT
            END DO
          END DO
        END DO
      END SELECT

      
    END SUBROUTINE BCINFLOWSUPERSONIC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCOUTFLOW(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
          
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCOUTFLOW
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCOUTFLOWSUBSONIC(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            CALL VARIABLE%SETPV(1,I,J,0.D0)
            DO M=2,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
      
    END SUBROUTINE BCOUTFLOWSUBSONIC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCOUTFLOWSUPERSONIC(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
    
    END SUBROUTINE BCOUTFLOWSUPERSONIC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCFARFIELD(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: NX(2),VEL
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETCX(BCINFO%IEND(1),J)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            VEL = (PV(2)*NX(1)+PV(3)*NX(2))/DSQRT(NX(1)**2+NX(2)**2)
            IF(VEL/DSQRT(DV(6)).GE.0.D0) THEN !OUT
              IF(VEL/DSQRT(DV(6)).GE.1.D0) THEN !SUPER                
                DO M=1,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            ELSE ! IN
              IF(VEL/DSQRT(DV(6)).LE.-1.D0) THEN !SUPER
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  SELECT CASE(M)
                  CASE(3)
                    CALL VARIABLE%SETTV(M,I,J,TV(M))
                  CASE DEFAULT
                    CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
                  END SELECT
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,PV(1))
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            END IF
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETCX(BCINFO%ISTART(1)-1,J)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            VEL = (PV(2)*NX(1)+PV(3)*NX(2))/DSQRT(NX(1)**2+NX(2)**2)
            IF(VEL/DSQRT(DV(6)).GE.0.D0) THEN !OUT
              IF(VEL/DSQRT(DV(6)).GE.1.D0) THEN !SUPER
                DO M=1,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            ELSE ! IN
              IF(VEL/DSQRT(DV(6)).LE.-1.D0) THEN !SUPER
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  SELECT CASE(M)
                  CASE(3)
                    CALL VARIABLE%SETTV(M,I,J,TV(M))
                  CASE DEFAULT
                    CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
                  END SELECT
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,PV(1))
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            END IF
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETEX(I,BCINFO%IEND(2))
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            VEL = (PV(2)*NX(1)+PV(3)*NX(2))/DSQRT(NX(1)**2+NX(2)**2)
            IF(VEL/DSQRT(DV(6)).GE.0.D0) THEN !OUT
              IF(VEL/DSQRT(DV(6)).GE.1.D0) THEN !SUPER
                DO M=1,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            ELSE ! IN
              IF(VEL/DSQRT(DV(6)).LE.-1.D0) THEN !SUPER
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  SELECT CASE(M)
                  CASE(3)
                    CALL VARIABLE%SETTV(M,I,J,TV(M))
                  CASE DEFAULT
                    CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
                  END SELECT
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,PV(1))
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            END IF
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETEX(I,BCINFO%ISTART(2)-1)
            PV = VARIABLE%GETPV(I,BCINFO%ISTART(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%ISTART(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%ISTART(2)-1)
            VEL = (PV(2)*NX(1)+PV(3)*NX(2))/DSQRT(NX(1)**2+NX(2)**2)
            IF(VEL/DSQRT(DV(6)).GE.0.D0) THEN !OUT
              IF(VEL/DSQRT(DV(6)).GE.1.D0) THEN !SUPER
                DO M=1,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,PV(M))
                END DO
                CALL EOS%DETEOS(REF%PV(1),PV(4),PV(5),PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),PV(4),PV(5),PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO           
              END IF
            ELSE ! IN
              IF(VEL/DSQRT(DV(6)).LE.-1.D0) THEN !SUPER
                CALL VARIABLE%SETPV(1,I,J,0.D0)
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,REF%DV(M))
                END DO
                DO M=1,VARIABLE%GETNTV()
                  SELECT CASE(M)
                  CASE(3)
                    CALL VARIABLE%SETTV(M,I,J,TV(M))
                  CASE DEFAULT
                    CALL VARIABLE%SETTV(M,I,J,REF%TV(M))
                  END SELECT
                END DO
              ELSE !SUB
                CALL VARIABLE%SETPV(1,I,J,PV(1))
                DO M=2,VARIABLE%GETNPV()
                  CALL VARIABLE%SETPV(M,I,J,REF%PV(M))
                END DO
                CALL EOS%DETEOS(PV(1)+REF%PV(1),REF%PV(4),REF%PV(5),REF%PV(6),DV)
                DO M=1,VARIABLE%GETNDV()
                  CALL VARIABLE%SETDV(M,I,J,DV(M))
                END DO
                IF(VARIABLE%GETNTV().NE.0) CALL PROP%DETPROP(DV(3),DV(4),DV(5),REF%PV(4),REF%PV(5),REF%PV(6),TV(1:2))
                DO M=1,VARIABLE%GETNTV()
                  CALL VARIABLE%SETTV(M,I,J,TV(M))
                END DO
              END IF
            END IF
          END DO
        END DO
      END SELECT
    
    END SUBROUTINE BCFARFIELD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCDEGENERATEPOINT(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%IEND(1)+1,J)
            DV = VARIABLE%GETDV(BCINFO%IEND(1)+1,J)
            TV = VARIABLE%GETTV(BCINFO%IEND(1)+1,J)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(BCINFO%ISTART(1)-1,J)
            DV = VARIABLE%GETDV(BCINFO%ISTART(1)-1,J)
            TV = VARIABLE%GETTV(BCINFO%ISTART(1)-1,J)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)+1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)+1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)+1)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            PV = VARIABLE%GETPV(I,BCINFO%IEND(2)-1)
            DV = VARIABLE%GETDV(I,BCINFO%IEND(2)-1)
            TV = VARIABLE%GETTV(I,BCINFO%IEND(2)-1)
            DO M=1,VARIABLE%GETNPV()
              CALL VARIABLE%SETPV(M,I,J,PV(M))
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
    
    END SUBROUTINE BCDEGENERATEPOINT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE BCSYMMETRYPLANE(BCINFO,REF,GRID,VARIABLE,EOS,PROP)
      IMPLICIT NONE
      CLASS(T_BCINFO_P), INTENT(IN) :: BCINFO
      TYPE(T_REF), INTENT(IN) :: REF
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      TYPE(T_EOS), INTENT(IN) :: EOS
      TYPE(T_PROP), INTENT(IN) :: PROP
      INTEGER :: I,J,M,II,JJ
      REAL(8) :: PV(VARIABLE%GETNPV()),DV(VARIABLE%GETNDV()),TV(VARIABLE%GETNTV())
      REAL(8) :: VAR,NX(2)
      
      SELECT CASE(BCINFO%FACE)
      CASE('IMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETCX(BCINFO%IEND(1),J)
            II = BCINFO%IEND(1)-I + BCINFO%IEND(1)+1
            PV = VARIABLE%GETPV(II,J)
            DV = VARIABLE%GETDV(II,J)
            TV = VARIABLE%GETTV(II,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('IMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETCX(BCINFO%ISTART(1)-1,J)
            II = BCINFO%ISTART(1)-I + BCINFO%ISTART(1)-1
            PV = VARIABLE%GETPV(II,J)
            DV = VARIABLE%GETDV(II,J)
            TV = VARIABLE%GETTV(II,J)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMIN')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = GRID%GETEX(I,BCINFO%IEND(2))
            JJ = BCINFO%IEND(2)-J + BCINFO%IEND(2)+1
            PV = VARIABLE%GETPV(I,JJ)
            DV = VARIABLE%GETDV(I,JJ)
            TV = VARIABLE%GETTV(I,JJ)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      CASE('JMAX')
        DO J=BCINFO%ISTART(2),BCINFO%IEND(2)
          DO I=BCINFO%ISTART(1),BCINFO%IEND(1)
            NX = - GRID%GETEX(I,BCINFO%ISTART(2)-1)
            JJ = BCINFO%ISTART(2)-J + BCINFO%ISTART(2)-1
            PV = VARIABLE%GETPV(I,JJ)
            DV = VARIABLE%GETDV(I,JJ)
            TV = VARIABLE%GETTV(I,JJ)
            DO M=1,VARIABLE%GETNPV()
              SELECT CASE(M)
              CASE(2)
                VAR = PV(2)-2.D0*NX(1)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE(3)
                VAR = PV(3)-2.D0*NX(2)*(PV(2)*NX(1)+PV(3)*NX(2))/(NX(1)**2+NX(2)**2)
                CALL VARIABLE%SETPV(M,I,J,VAR)
              CASE DEFAULT
                CALL VARIABLE%SETPV(M,I,J,PV(M))
              END SELECT
            END DO
            DO M=1,VARIABLE%GETNDV()
              CALL VARIABLE%SETDV(M,I,J,DV(M))
            END DO
            DO M=1,VARIABLE%GETNTV()
              CALL VARIABLE%SETTV(M,I,J,TV(M))
            END DO
          END DO
        END DO
      END SELECT
    END SUBROUTINE BCSYMMETRYPLANE
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE BC_MODULE