MODULE CONFIG_MODULE
  USE EOS_MODULE
  USE PROP_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_CONFIG
  
  TYPE T_CONFIG
    PRIVATE
    LOGICAL, PUBLIC :: STATUS
    CHARACTER(3) :: CPUNUM
    CHARACTER(30) :: NAME
    INTEGER :: RANK,SIZE
    INTEGER :: IREAD,RSTNUM
    INTEGER :: NSTEADY,NPMAX,NTMAX,BOND
    REAL(8) :: DT_PHY
    INTEGER :: NEXPORT,NPRINT
    INTEGER :: ITURB,TCOMP
    INTEGER :: NSCHEME,PRECD,NMUSCL,NLIM
    INTEGER :: TIMEMETHOD,LOCAL,PREC
    REAL(8) :: CFL
    INTEGER :: FLUID,FLUID_EOSTYPE,NGAS,GAS_EOSTYPE,MIXINGRULE
    INTEGER :: NCAV
    REAL(8) :: C_V,C_C
    REAL(8) :: PREF,UREF,AOA,TREF,Y1REF,Y2REF
    REAL(8) :: L_CHORD,L_CHARACTER,SCALE
    REAL(8) :: STR,PI
    REAL(8) :: DVREF(18),TVREF(2)
    REAL(8) :: KREF,OREF,EMUTREF
    CONTAINS
      PROCEDURE :: CONSTRUCT
      PROCEDURE :: DESTRUCT
      PROCEDURE :: GETRANK
      PROCEDURE :: GETSIZE
      PROCEDURE :: GETNAME
      PROCEDURE :: GETIREAD
      PROCEDURE :: GETNSTEADY
      PROCEDURE :: GETNPMAX
      PROCEDURE :: GETNTMAX
      PROCEDURE :: GETBOND
      PROCEDURE :: GETDT_PHY
      PROCEDURE :: GETNEXPORT
      PROCEDURE :: GETNPRINT
      PROCEDURE :: GETRSTNUM
      PROCEDURE :: GETITURB
      PROCEDURE :: GETNSCHEME
      PROCEDURE :: GETPRECD
      PROCEDURE :: GETNMUSCL
      PROCEDURE :: GETNLIM
      PROCEDURE :: GETTIMEMETHOD
      PROCEDURE :: GETLOCAL
      PROCEDURE :: GETPREC
      PROCEDURE :: GETNCAV
      PROCEDURE :: GETTCOMP
      PROCEDURE :: GETC_V
      PROCEDURE :: GETC_C
      PROCEDURE :: GETCFL
      PROCEDURE :: GETPREF
      PROCEDURE :: GETUREF
      PROCEDURE :: GETAOA
      PROCEDURE :: GETTREF
      PROCEDURE :: GETY1REF
      PROCEDURE :: GETY2REF
      PROCEDURE :: GETRHOREF
      PROCEDURE :: GETVISREF
      PROCEDURE :: GETKREF
      PROCEDURE :: GETOREF
      PROCEDURE :: GETEMUTREF
      PROCEDURE :: GETL_CHORD
      PROCEDURE :: GETL_CHARACTER
      PROCEDURE :: GETSCALE
      PROCEDURE :: GETSTR
      PROCEDURE :: GETPI
  END TYPE T_CONFIG
    
  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CONSTRUCT(CONFIG,EOS,PROP)
      IMPLICIT NONE
      INCLUDE 'mpif.h'
      CLASS(T_CONFIG), INTENT(OUT) :: CONFIG
      TYPE(T_EOS), INTENT(OUT) :: EOS
      TYPE(T_PROP), INTENT(OUT) :: PROP
      INTEGER :: N,IO,IERR
    
      CALL MPI_INIT(IERR)
      CALL MPI_COMM_SIZE(MPI_COMM_WORLD,CONFIG%SIZE,IERR)
      CALL MPI_COMM_RANK(MPI_COMM_WORLD,CONFIG%RANK,IERR)
      WRITE(CONFIG%CPUNUM,'(I3.3)') CONFIG%RANK
    
      DO N = 0,CONFIG%SIZE-1
        IF(N.EQ.CONFIG%RANK) THEN
          OPEN(NEWUNIT=IO,FILE='./INPUT.INP',STATUS='OLD',ACTION='READ')
          READ(IO,*); READ(IO,*) CONFIG%NAME
          READ(IO,*); READ(IO,*) CONFIG%IREAD,CONFIG%RSTNUM
          READ(IO,*); READ(IO,*) CONFIG%NSTEADY,CONFIG%NPMAX,CONFIG%NTMAX,CONFIG%BOND,CONFIG%DT_PHY
          READ(IO,*); READ(IO,*) CONFIG%NEXPORT,CONFIG%NPRINT
          READ(IO,*); READ(IO,*) CONFIG%ITURB,CONFIG%TCOMP
          READ(IO,*); READ(IO,*) CONFIG%NSCHEME,CONFIG%PRECD,CONFIG%NMUSCL,CONFIG%NLIM
          READ(IO,*); READ(IO,*) CONFIG%TIMEMETHOD,CONFIG%LOCAL,CONFIG%PREC,CONFIG%CFL
          READ(IO,*); READ(IO,*) CONFIG%FLUID,CONFIG%FLUID_EOSTYPE,CONFIG%NGAS,CONFIG%GAS_EOSTYPE,CONFIG%MIXINGRULE
          READ(IO,*); READ(IO,*) CONFIG%NCAV,CONFIG%C_V,CONFIG%C_C
          READ(IO,*); READ(IO,*) CONFIG%PREF,CONFIG%UREF,CONFIG%AOA,CONFIG%TREF,CONFIG%Y1REF,CONFIG%Y2REF
          READ(IO,*); READ(IO,*) CONFIG%L_CHORD,CONFIG%L_CHARACTER,CONFIG%SCALE
          CLOSE(IO)
        ENDIF
        CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
      END DO
      
      CALL EOS%CONSTRUCT(CONFIG%FLUID,CONFIG%FLUID_EOSTYPE,CONFIG%NGAS,CONFIG%GAS_EOSTYPE,CONFIG%MIXINGRULE)
      CALL PROP%CONSTRUCT(CONFIG%FLUID,CONFIG%FLUID_EOSTYPE,CONFIG%NGAS)
      
      
      CONFIG%PI  = DATAN(1.D0)*4.D0
      CONFIG%AOA = CONFIG%AOA*CONFIG%PI/180.D0
      CONFIG%STR = CONFIG%L_CHARACTER/CONFIG%PI/CONFIG%DT_PHY/CONFIG%UREF
      
      CALL EOS%DETEOS(CONFIG%PREF,CONFIG%TREF,CONFIG%Y1REF,CONFIG%Y2REF,CONFIG%DVREF)
      CALL PROP%DETPROP(CONFIG%DVREF(3),CONFIG%DVREF(4),CONFIG%DVREF(5),CONFIG%TREF,CONFIG%Y1REF,CONFIG%Y2REF,CONFIG%TVREF)
      
      
      IF(CONFIG%ITURB.EQ.0) THEN
        CONFIG%OREF = 10.D0*CONFIG%UREF/CONFIG%L_CHARACTER
        CONFIG%EMUTREF = 10.D0**(-5)*CONFIG%TVREF(1)
        CONFIG%KREF = CONFIG%EMUTREF/CONFIG%DVREF(1)*CONFIG%OREF
      ELSE IF(CONFIG%ITURB.EQ.-1) THEN
        CONFIG%KREF = 1.5D0*(0.0001D0*CONFIG%UREF)**2
        CONFIG%EMUTREF =  10.D0**(-5)*CONFIG%TVREF(1)
        CONFIG%OREF = 0.09D0*CONFIG%DVREF(1)*CONFIG%KREF**2/CONFIG%EMUTREF
      ELSE
        CONFIG%KREF = 0.D0
        CONFIG%OREF = 0.D0
        CONFIG%EMUTREF =  0.D0    
      END IF
      
      CONFIG%STATUS = .TRUE.
    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE DESTRUCT(CONFIG,EOS,PROP)
      IMPLICIT NONE
      INCLUDE 'mpif.h'
      CLASS(T_CONFIG), INTENT(INOUT) :: CONFIG
      TYPE(T_EOS), INTENT(INOUT) :: EOS
      TYPE(T_PROP), INTENT(INOUT) :: PROP
      INTEGER :: IERR
      
      CONFIG%STATUS = .FALSE.      
      CALL EOS%DESTRUCT()
      CALL PROP%DESTRUCT()
      
      CALL MPI_FINALIZE(IERR)
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC    
    FUNCTION GETRANK(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETRANK
      
      GETRANK = CONFIG%RANK
      
    END FUNCTION GETRANK
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETSIZE(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETSIZE
      
      GETSIZE = CONFIG%SIZE
      
    END FUNCTION GETSIZE
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNAME(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      CHARACTER(30) :: GETNAME
      
      GETNAME = CONFIG%NAME
      
    END FUNCTION GETNAME
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETIREAD(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETIREAD
      
      GETIREAD = CONFIG%IREAD
      
    END FUNCTION GETIREAD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNSTEADY(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNSTEADY
      
      GETNSTEADY = CONFIG%NSTEADY
      
    END FUNCTION GETNSTEADY
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNPMAX(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNPMAX
      
      GETNPMAX = CONFIG%NPMAX
      
    END FUNCTION GETNPMAX
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNTMAX(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNTMAX
      
      GETNTMAX = CONFIG%NTMAX
      
    END FUNCTION GETNTMAX
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETBOND(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETBOND
      
      GETBOND = CONFIG%BOND
      
    END FUNCTION GETBOND
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETDT_PHY(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETDT_PHY
      
      GETDT_PHY = CONFIG%DT_PHY
      
    END FUNCTION GETDT_PHY
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNEXPORT(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNEXPORT
      
      GETNEXPORT = CONFIG%NEXPORT
      
    END FUNCTION GETNEXPORT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNPRINT(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNPRINT
      
      GETNPRINT = CONFIG%NPRINT
      
    END FUNCTION GETNPRINT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETRSTNUM(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETRSTNUM
      
      GETRSTNUM = CONFIG%RSTNUM
      
    END FUNCTION GETRSTNUM
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETITURB(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETITURB
      
      GETITURB = CONFIG%ITURB
      
    END FUNCTION GETITURB
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNSCHEME(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNSCHEME
      
      GETNSCHEME = CONFIG%NSCHEME
      
    END FUNCTION GETNSCHEME
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETPRECD(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETPRECD
      
      GETPRECD = CONFIG%PRECD
      
    END FUNCTION GETPRECD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNMUSCL(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNMUSCL
      
      GETNMUSCL = CONFIG%NMUSCL
      
    END FUNCTION GETNMUSCL
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNLIM(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNLIM
      
      GETNLIM = CONFIG%NLIM
    END FUNCTION GETNLIM
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETTIMEMETHOD(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETTIMEMETHOD
      
      GETTIMEMETHOD = CONFIG%TIMEMETHOD
      
    END FUNCTION GETTIMEMETHOD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETLOCAL(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETLOCAL
      
      GETLOCAL = CONFIG%LOCAL
      
    END FUNCTION GETLOCAL
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETPREC(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETPREC
      
      GETPREC = CONFIG%PREC
      
    END FUNCTION GETPREC
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETNCAV(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETNCAV
      
      GETNCAV = CONFIG%NCAV
      
    END FUNCTION GETNCAV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETTCOMP(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      INTEGER :: GETTCOMP
      
      GETTCOMP = CONFIG%TCOMP
      
    END FUNCTION GETTCOMP
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETC_V(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETC_V
      
      GETC_V = CONFIG%C_V
      
    END FUNCTION GETC_V
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETC_C(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETC_C
      
      GETC_C = CONFIG%C_C
      
    END FUNCTION GETC_C
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETCFL(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETCFL
      
      GETCFL = CONFIG%CFL
      
    END FUNCTION GETCFL
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETPREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETPREF
      
      GETPREF = CONFIG%PREF
      
    END FUNCTION GETPREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETUREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETUREF
      
      GETUREF = CONFIG%UREF
      
    END FUNCTION GETUREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETAOA(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETAOA
      
      GETAOA = CONFIG%AOA
      
    END FUNCTION GETAOA
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETTREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETTREF
      
      GETTREF = CONFIG%TREF
      
    END FUNCTION GETTREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETY1REF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETY1REF
      
      GETY1REF = CONFIG%Y1REF
    
    END FUNCTION GETY1REF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETY2REF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETY2REF
      
      GETY2REF = CONFIG%Y2REF
      
    END FUNCTION GETY2REF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETRHOREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETRHOREF
      
      GETRHOREF = CONFIG%DVREF(1)
      
    END FUNCTION GETRHOREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETVISREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETVISREF
      
      GETVISREF = CONFIG%TVREF(1)
      
    END FUNCTION GETVISREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETKREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETKREF
      
      GETKREF = CONFIG%KREF
      
    END FUNCTION GETKREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETOREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETOREF
      
      GETOREF = CONFIG%OREF
      
    END FUNCTION GETOREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETEMUTREF(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETEMUTREF
      
      GETEMUTREF = CONFIG%EMUTREF
      
    END FUNCTION GETEMUTREF
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETL_CHORD(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETL_CHORD
      
      GETL_CHORD = CONFIG%L_CHORD
      
    END FUNCTION GETL_CHORD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETL_CHARACTER(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETL_CHARACTER
      
      GETL_CHARACTER = CONFIG%L_CHARACTER
      
    END FUNCTION GETL_CHARACTER
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    FUNCTION GETSCALE(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETSCALE
      
      GETSCALE = CONFIG%SCALE
      
    END FUNCTION GETSCALE
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETSTR(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETSTR
      
      GETSTR = CONFIG%STR
      
    END FUNCTION GETSTR
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETPI(CONFIG)
      IMPLICIT NONE
      CLASS(T_CONFIG), INTENT(IN) :: CONFIG
      REAL(8) :: GETPI
      
      GETPI = CONFIG%PI
      
    END FUNCTION GETPI
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE CONFIG_MODULE