MODULE DATAWRITING_MODULE
  USE CONFIG_MODULE
  USE GRID_MODULE
  USE POSTVARIABLE_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_DATAWRITING
  
  TYPE T_DATAWRITING
  
    CONTAINS
      PROCEDURE :: CGNSWRITING
      PROCEDURE :: CL_WRITING
  END TYPE T_DATAWRITING
  
  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CGNSWRITING(DATAWRITING,CONFIG,VARIABLE)
      IMPLICIT NONE
      INCLUDE 'cgnslib_f.h'
      CLASS(T_DATAWRITING), INTENT(INOUT) :: DATAWRITING
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: IFILE,IER,INDEX_FLOW,INDEX_FIELD
      INTEGER :: N,M,L,I,J,K
      REAL(8), DIMENSION(:), ALLOCATABLE :: TIME
      REAL(8), DIMENSION(:,:,:,:), ALLOCATABLE :: PV,DV,TV
      REAL(8), DIMENSION(:,:,:), ALLOCATABLE :: A
      CHARACTER(7), DIMENSION(:), ALLOCATABLE :: SOLNAME
 
      ALLOCATE(SOLNAME(VARIABLE%GETNSOLUTION()),TIME(VARIABLE%GETNSOLUTION()))
      
      IF(CONFIG%GETNSTEADY().EQ.1) THEN
        DO N=1,VARIABLE%GETNSOLUTION()
          WRITE(SOLNAME(N),'(I4.4)') VARIABLE%GETNPS(N)
          TIME(N) = DBLE(VARIABLE%GETNPS(N))
        END DO      
      ELSE
        DO N=1,VARIABLE%GETNSOLUTION()
          WRITE(SOLNAME(N),'(I7.7)') VARIABLE%GETNTS(N)
          TIME(N) = DBLE(VARIABLE%GETNTS(N))
        END DO      
      END IF

      
      CALL CG_OPEN_F('./'//TRIM(CONFIG%GETNAME())//'.cgns',CG_MODE_READ,IFILE,IER)
      IF(IER.NE.CG_OK) CALL CG_ERROR_EXIT_F
      CALL CG_SAVE_AS_F(IFILE,'./'//TRIM(CONFIG%GETNAME())//'_RESULT.cgns',CG_FILE_HDF5,0,IER)
      CALL CG_CLOSE_F(IFILE,IER)
      
      CALL CG_OPEN_F('./'//TRIM(CONFIG%GETNAME())//'_RESULT.cgns',CG_MODE_MODIFY,IFILE,IER)
      IF(IER.NE.CG_OK) CALL CG_ERROR_EXIT_F
      
      DO N=1,VARIABLE%GETNSOLUTION()
        WRITE(*,*) 'SOLUTION=',N, 'NPS=',VARIABLE%GETNPS(N), 'NTS=',VARIABLE%GETNTS(N)
        DO M=0,VARIABLE%GETSIZE(N)-1
          WRITE(*,*) 'WRITING VARIABLES TO DOMAIN',M+1
          ALLOCATE(PV(VARIABLE%GETIMAX(N,M)-1,VARIABLE%GETJMAX(N,M)-1,VARIABLE%GETKMAX(N,M)-1,VARIABLE%GETNPV()))
          ALLOCATE(DV(VARIABLE%GETIMAX(N,M)-1,VARIABLE%GETJMAX(N,M)-1,VARIABLE%GETKMAX(N,M)-1,VARIABLE%GETNDV()))
          ALLOCATE(TV(VARIABLE%GETIMAX(N,M)-1,VARIABLE%GETJMAX(N,M)-1,VARIABLE%GETKMAX(N,M)-1,VARIABLE%GETNTV()))
          ALLOCATE(A(VARIABLE%GETIMAX(N,M)-1,VARIABLE%GETJMAX(N,M)-1,VARIABLE%GETKMAX(N,M)-1))
          
          DO K=2,VARIABLE%GETKMAX(N,M)
            DO J=2,VARIABLE%GETJMAX(N,M)
              DO I=2,VARIABLE%GETIMAX(N,M)
                DO L=1,VARIABLE%GETNPV()
                  PV(I-1,J-1,K-1,L) = VARIABLE%GETPV(N,M,L,I,J,K)
                END DO
                DO L=1,VARIABLE%GETNDV()
                  DV(I-1,J-1,K-1,L) = VARIABLE%GETDV(N,M,L,I,J,K)
                END DO
                DO L=1,VARIABLE%GETNTV()
                  TV(I-1,J-1,K-1,L) = VARIABLE%GETTV(N,M,L,I,J,K)
                END DO
              END DO
            END DO
          END DO
          
          A = DSQRT(DV(:,:,:,6))
          CALL CG_SOL_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,SOLNAME(N),CellCenter,INDEX_FLOW,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'PRESSURE',PV(:,:,:,1),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'UVELOCITY',PV(:,:,:,2),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'VVELOCITY',PV(:,:,:,3),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'WVELOCITY',PV(:,:,:,4),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'TEMPERATURE',PV(:,:,:,5),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'Y1',PV(:,:,:,6),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'Y2',PV(:,:,:,7),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'DENSITY',DV(:,:,:,1),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'ENTHALPY',DV(:,:,:,2),INDEX_FIELD,IER)
          CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'SOS',A,INDEX_FIELD,IER)
          IF(CONFIG%GETITURB().GE.-1) THEN
            CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'K',PV(:,:,:,8),INDEX_FIELD,IER)
            CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'OMEGA',PV(:,:,:,9),INDEX_FIELD,IER)
            CALL CG_FIELD_WRITE_F(IFILE,1,VARIABLE%GETRANK(N,M)+1,INDEX_FLOW,RealDouble,'EMUT',TV(:,:,:,3),INDEX_FIELD,IER)
          END IF
          DEALLOCATE(PV,DV,TV,A)
        END DO
        WRITE(*,*) '-----------------------------------------------------------'
      END DO
      
      CALL CG_BITER_WRITE_F(IFILE,1,'TimeIterValues',VARIABLE%GETNSOLUTION(),IER)
      CALL CG_GOTO_F(IFILE,1,IER,'BaseIterativeData_t',1,'end')
      CALL CG_ARRAY_WRITE_F('TimeValues',RealDouble,1,VARIABLE%GETNSOLUTION(),TIME,IER)
      
      CALL CG_CLOSE_F(IFILE,IER)
      DEALLOCATE(SOLNAME,TIME)
    END SUBROUTINE CGNSWRITING
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CL_WRITING(DATAWRITING,CONFIG,GRID,VARIABLE)
      IMPLICIT NONE
      CLASS(T_DATAWRITING), INTENT(INOUT) :: DATAWRITING
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: IO,N,M,I,J
      REAL(8) :: CX(2),CL1,CL2,CL
      
      !OPEN(NEWUNIT=IO,FILE='./CL_'//TRIM(CONFIG%GETNAME())//'.DAT',STATUS='UNKNOWN',ACTION='WRITE',FORM='FORMATTED')
      !WRITE(IO,*) 'VARIABLES = "TIME", "CL"'
      !WRITE(IO,*) 'ZONE T = " ",I=',VARIABLE%GETNSOLUTION()
      !DO N=1,VARIABLE%GETNSOLUTION()
      !  DO M=1,GRID%GETNBC()
      !    IF((TRIM(GRID%GETBCNAME(M)).EQ.'BCWallInviscid').OR.(TRIM(GRID%GETBCNAME(M)).EQ.'BCWallViscous')) THEN
      !      CL1 = 0.D0
      !      CL2 = 0.D0
      !      IF(GRID%GETBCISTART(M,2).EQ.GRID%GETBCIEND(M,2)) THEN
      !        IF(GRID%GETBCISTART(M,2).EQ.1) THEN !JMIN
      !          DO J=GRID%GETBCISTART(M,2),GRID%GETBCIEND(M,2)
      !            DO I=GRID%GETBCISTART(M,1),GRID%GETBCIEND(M,1)
      !              CX = GRID%GETEX(I,J)
      !              CL1 = CL1 + VARIABLE%GETPV(N,0,1,I,J+1)*CX(1)
      !              CL2 = CL2 + VARIABLE%GETPV(N,0,1,I,J+1)*CX(2)
      !            END DO
      !          END DO
      !        ELSE                                !JMAX
      !          DO J=GRID%GETBCISTART(M,2),GRID%GETBCIEND(M,2)
      !            DO I=GRID%GETBCISTART(M,1),GRID%GETBCIEND(M,1)
      !              CX = - GRID%GETEX(I,J-1)
      !              CL1 = CL1 + VARIABLE%GETPV(N,0,1,I,J-1)*CX(1)
      !              CL2 = CL2 + VARIABLE%GETPV(N,0,1,I,J-1)*CX(2)
      !            END DO
      !          END DO
      !        END IF
      !      ELSE IF(GRID%GETBCISTART(M,1).EQ.GRID%GETBCIEND(M,1)) THEN
      !        IF(GRID%GETBCISTART(M,1).EQ.1) THEN !IMIN
      !          DO J=GRID%GETBCISTART(M,2),GRID%GETBCIEND(M,2)
      !            DO I=GRID%GETBCISTART(M,1),GRID%GETBCIEND(M,1)
      !              CX = GRID%GETCX(I,J)
      !              CL1 = CL1 + VARIABLE%GETPV(N,0,1,I+1,J)*CX(1)
      !              CL2 = CL2 + VARIABLE%GETPV(N,0,1,I+1,J)*CX(2)
      !            END DO
      !          END DO
      !        ELSE                                !IMAX
      !          DO J=GRID%GETBCISTART(M,2),GRID%GETBCIEND(M,2)
      !            DO I=GRID%GETBCISTART(M,1),GRID%GETBCIEND(M,1)
      !              CX = - GRID%GETCX(I-1,J)
      !              CL1 = CL1 + VARIABLE%GETPV(N,0,1,I-1,J)*CX(1)
      !              CL2 = CL2 + VARIABLE%GETPV(N,0,1,I-1,J)*CX(2)
      !            END DO
      !          END DO
      !        END IF
      !      END IF
      !    END IF
      !  END DO
      !  CL1 = CL1/(0.5D0*CONFIG%GETRHOREF()*CONFIG%GETUREF()**2)/CONFIG%GETL_CHORD()
      !  CL2 = CL2/(0.5D0*CONFIG%GETRHOREF()*CONFIG%GETUREF()**2)/CONFIG%GETL_CHORD()
      !  CL = DSIN(CONFIG%GETAOA())*CL1+DCOS(CONFIG%GETAOA())*CL2
      !  WRITE(IO,*) N,CL
      !END DO
      !CLOSE(IO)
      
    END SUBROUTINE CL_WRITING
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE DATAWRITING_MODULE