MODULE EDDY_MODULE
  USE GRID_MODULE
  USE VARIABLE_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_EDDY,T_EDDY_KE,T_EDDY_KWSST
  
  TYPE, ABSTRACT :: T_EDDY
    PRIVATE
    INTEGER :: NPV,NDV,NTV,NGRD
    REAL(8), POINTER :: PV(:,:)
    REAL(8), POINTER :: CX1(:),CX2(:),EX1(:),EX2(:),TX1(:),TX2(:)
    REAL(8), POINTER :: DV(:),TV(:),GRD(:)
    CONTAINS
      PROCEDURE :: CONSTRUCT
      PROCEDURE :: DESTRUCT
      PROCEDURE :: SETNORM ! (CX1,CX2,EX1,EX2,TX1,TX2)
      PROCEDURE :: SETGRD  ! VOL,XCEN,YCEN,ZCEN,YDNS
      PROCEDURE :: SETPV   ! P,U,V,W,T,Y1,Y2,K,O
      PROCEDURE :: SETDV   ! RHO,H,RHOL,RHOV,RHOG,SND2,DRDP,DRDT,DRDY1,DRDY2,DHDP,DHDT,DHDY1,DHDY2,DRDPV,DRDTV,DRDPL,DRDTL
      PROCEDURE :: SETTV   ! VIS,COND,EMUT
      PROCEDURE(P_CALEDDY), DEFERRED :: CALEDDY
  END TYPE T_EDDY
  
  ABSTRACT INTERFACE
    FUNCTION P_CALEDDY(EDDY) RESULT(EMUT)
      IMPORT T_EDDY
      CLASS(T_EDDY), INTENT(IN) :: EDDY
      REAL(8) :: EMUT
    END FUNCTION P_CALEDDY
  END INTERFACE
  
  TYPE, EXTENDS(T_EDDY) :: T_EDDY_KE
    CONTAINS
      PROCEDURE :: CALEDDY => KEPSILON
  END TYPE T_EDDY_KE

  TYPE, EXTENDS(T_EDDY) :: T_EDDY_KWSST
    CONTAINS
      PROCEDURE :: CALEDDY => KWSST
  END TYPE T_EDDY_KWSST

  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CONSTRUCT(EDDY,GRID,VARIABLE)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(OUT) :: EDDY
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(IN) :: VARIABLE
    
      EDDY%NGRD = GRID%GETNGRD()
      EDDY%NPV  = VARIABLE%GETNPV()
      EDDY%NDV  = VARIABLE%GETNDV()
      EDDY%NTV  = VARIABLE%GETNTV()

    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE DESTRUCT(EDDY)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      
      IF(ASSOCIATED(EDDY%CX1))     NULLIFY(EDDY%CX1)
      IF(ASSOCIATED(EDDY%CX2))     NULLIFY(EDDY%CX2)
      IF(ASSOCIATED(EDDY%EX1))     NULLIFY(EDDY%EX1)
      IF(ASSOCIATED(EDDY%EX2))     NULLIFY(EDDY%EX2)
      IF(ASSOCIATED(EDDY%TX1))     NULLIFY(EDDY%TX1)
      IF(ASSOCIATED(EDDY%TX2))     NULLIFY(EDDY%TX2)
      IF(ASSOCIATED(EDDY%GRD))     NULLIFY(EDDY%GRD)
      IF(ASSOCIATED(EDDY%PV))      NULLIFY(EDDY%PV) 
      IF(ASSOCIATED(EDDY%DV))      NULLIFY(EDDY%DV) 
      IF(ASSOCIATED(EDDY%TV))      NULLIFY(EDDY%TV) 
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETNORM(EDDY,CX1,CX2,EX1,EX2,TX1,TX2)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      REAL(8), INTENT(IN), TARGET :: CX1(3),CX2(3),EX1(3),EX2(3),TX1(3),TX2(3)
      
      EDDY%CX1 => CX1
      EDDY%CX2 => CX2
      EDDY%EX1 => EX1
      EDDY%EX2 => EX2
      EDDY%TX1 => TX1
      EDDY%TX2 => TX2
      
    END SUBROUTINE SETNORM
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETGRD(EDDY,GRD)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      REAL(8), INTENT(IN), TARGET :: GRD(EDDY%NGRD)
      
      EDDY%GRD => GRD
    
    END SUBROUTINE SETGRD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETPV(EDDY,PV)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      REAL(8), INTENT(IN), TARGET :: PV(7,EDDY%NPV)
      
      EDDY%PV => PV
      
    END SUBROUTINE SETPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETDV(EDDY,DV)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      REAL(8), INTENT(IN), TARGET :: DV(EDDY%NDV)
      
      EDDY%DV => DV
    
    END SUBROUTINE SETDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETTV(EDDY,TV)
      IMPLICIT NONE
      CLASS(T_EDDY), INTENT(INOUT) :: EDDY
      REAL(8), INTENT(IN), TARGET :: TV(EDDY%NTV)
      
      EDDY%TV => TV
    
    END SUBROUTINE SETTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION KEPSILON(EDDY) RESULT(EMUT)
      CLASS(T_EDDY_KE), INTENT(IN) :: EDDY
      REAL(8) :: EMUT
      REAL(8) :: RE_T,RE_E,F_MU
      
      RE_T = EDDY%DV(1)*EDDY%PV(2,8)**2/EDDY%PV(2,9)/EDDY%TV(1)
      RE_E = EDDY%DV(1)*(EDDY%TV(1)/EDDY%DV(1)*EDDY%PV(2,9))**0.25D0*EDDY%GRD(5)/EDDY%TV(1)
      F_MU = (1.D0+3.D0/RE_T**(3.D0/4.D0))*(1.D0+80.D0*DEXP(-RE_E))*(1.D0-DEXP(-RE_E/43.D0-RE_E**2/330.D0))**2
      EMUT = 0.09D0*EDDY%DV(1)*EDDY%PV(2,8)**2/EDDY%PV(2,9)*F_MU    
    END FUNCTION KEPSILON
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION KWSST(EDDY) RESULT(EMUT)
      CLASS(T_EDDY_KWSST), INTENT(IN) :: EDDY
      REAL(8) :: EMUT
      REAL(8) :: U1,U2,U3,U4,U5,U6
      REAL(8) :: V1,V2,V3,V4,V5,V6
      REAL(8) :: W1,W2,W3,W4,W5,W6
      REAL(8) :: DUDX,DUDY,DUDZ,DVDX,DVDY,DVDZ,DWDX,DWDY,DWDZ
      REAL(8) :: TERM1,TERM2,ARG2,BIGF2
      REAL(8) :: SIJSIJ,SSS,TERM4,TERM5,TERM6

      U1 = 0.5D0*(EDDY%PV(1,2)+EDDY%PV(2,2))
      U2 = 0.5D0*(EDDY%PV(3,2)+EDDY%PV(2,2))
      U3 = 0.5D0*(EDDY%PV(4,2)+EDDY%PV(2,2))
      U4 = 0.5D0*(EDDY%PV(5,2)+EDDY%PV(2,2))
      U5 = 0.5D0*(EDDY%PV(6,2)+EDDY%PV(2,2))
      U6 = 0.5D0*(EDDY%PV(7,2)+EDDY%PV(2,2))

      V1 = 0.5D0*(EDDY%PV(1,3)+EDDY%PV(2,3))
      V2 = 0.5D0*(EDDY%PV(3,3)+EDDY%PV(2,3))
      V3 = 0.5D0*(EDDY%PV(4,3)+EDDY%PV(2,3))
      V4 = 0.5D0*(EDDY%PV(5,3)+EDDY%PV(2,3))
      V5 = 0.5D0*(EDDY%PV(6,3)+EDDY%PV(2,3))
      V6 = 0.5D0*(EDDY%PV(7,3)+EDDY%PV(2,3))

      W1 = 0.5D0*(EDDY%PV(1,4)+EDDY%PV(2,4))
      W2 = 0.5D0*(EDDY%PV(3,4)+EDDY%PV(2,4))
      W3 = 0.5D0*(EDDY%PV(4,4)+EDDY%PV(2,4))
      W4 = 0.5D0*(EDDY%PV(5,4)+EDDY%PV(2,4))
      W5 = 0.5D0*(EDDY%PV(6,4)+EDDY%PV(2,4))
      W6 = 0.5D0*(EDDY%PV(7,4)+EDDY%PV(2,4))
      
      DUDX = (U2*EDDY%CX2(1)+U4*EDDY%EX2(1)+U6*EDDY%TX2(1)-U1*EDDY%CX1(1)-U3*EDDY%EX1(1)-U5*EDDY%TX1(1))/EDDY%GRD(1)
      DUDY = (U2*EDDY%CX2(2)+U4*EDDY%EX2(2)+U6*EDDY%TX2(2)-U1*EDDY%CX1(2)-U3*EDDY%EX1(2)-U5*EDDY%TX1(2))/EDDY%GRD(1)
      DUDY = (U2*EDDY%CX2(3)+U4*EDDY%EX2(3)+U6*EDDY%TX2(3)-U1*EDDY%CX1(3)-U3*EDDY%EX1(3)-U5*EDDY%TX1(3))/EDDY%GRD(1)
      DVDX = (V2*EDDY%CX2(1)+V4*EDDY%EX2(1)+V6*EDDY%TX2(1)-V1*EDDY%CX1(1)-V3*EDDY%EX1(1)-V5*EDDY%TX1(1))/EDDY%GRD(1)
      DVDY = (V2*EDDY%CX2(2)+V4*EDDY%EX2(2)+V6*EDDY%TX2(2)-V1*EDDY%CX1(2)-V3*EDDY%EX1(2)-V5*EDDY%TX1(2))/EDDY%GRD(1)
      DVDY = (V2*EDDY%CX2(3)+V4*EDDY%EX2(3)+V6*EDDY%TX2(3)-V1*EDDY%CX1(3)-V3*EDDY%EX1(3)-V5*EDDY%TX1(3))/EDDY%GRD(1)
      DWDX = (W2*EDDY%CX2(1)+W4*EDDY%EX2(1)+W6*EDDY%TX2(1)-W1*EDDY%CX1(1)-W3*EDDY%EX1(1)-W5*EDDY%TX1(1))/EDDY%GRD(1)
      DWDY = (W2*EDDY%CX2(2)+W4*EDDY%EX2(2)+W6*EDDY%TX2(2)-W1*EDDY%CX1(2)-W3*EDDY%EX1(2)-W5*EDDY%TX1(2))/EDDY%GRD(1)
      DWDY = (W2*EDDY%CX2(3)+W4*EDDY%EX2(3)+W6*EDDY%TX2(3)-W1*EDDY%CX1(3)-W3*EDDY%EX1(3)-W5*EDDY%TX1(3))/EDDY%GRD(1)
      
      TERM1 = DSQRT(EDDY%PV(2,8))/(0.09D0*EDDY%PV(2,9)*EDDY%GRD(5))
      TERM2 = 500.D0*EDDY%TV(1)/EDDY%DV(1)/(EDDY%PV(2,9)*EDDY%GRD(5)**2)
      ARG2 = DMAX1(2.D0*TERM1,TERM2)
      BIGF2 = DTANH(ARG2**2)   
      SIJSIJ = DUDX**2+DVDY**2+DWDZ**2+0.5D0*((DUDY+DVDX)**2+(DUDZ+DWDX)**2+(DVDZ+DWDY)**2)
      SSS = DSQRT(2.D0*SIJSIJ)
      TERM4 = 0.31D0*EDDY%PV(2,9)
      TERM5 = SSS*BIGF2
      TERM6 = DMAX1(TERM4,TERM5)
      EMUT = 0.31*EDDY%DV(1)*EDDY%PV(2,8)/TERM6
    END FUNCTION KWSST
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE EDDY_MODULE