PROGRAM CTFS3D
  USE CONFIG_MODULE
  USE EOS_MODULE
  USE PROP_MODULE
  USE GRID_MODULE
  USE VARIABLE_MODULE
  USE SOLVE_MODULE
  IMPLICIT NONE
  TYPE(T_CONFIG) :: CONFIG
  TYPE(T_EOS) :: EOS
  TYPE(T_PROP) :: PROP
  TYPE(T_GRID) :: GRID
  TYPE(T_VARIABLE) :: VARIABLE
  TYPE(T_SOLVE) :: SOLVE

  CALL CONFIG%CONSTRUCT(EOS,PROP) !EOS & PROP ARE ALSO CONSTRUCTED
  CALL GRID%CONSTRUCT(CONFIG)
  CALL VARIABLE%CONSTRUCT(CONFIG,GRID)
  CALL SOLVE%CONSTRUCT(CONFIG,GRID,VARIABLE,EOS,PROP)
  
  CALL SOLVE%SOLVE_EQUATION(GRID,VARIABLE,EOS,PROP)
  
  CALL SOLVE%DESTRUCT()
  CALL VARIABLE%DESTRUCT()
  CALL GRID%DESTRUCT()
  CALL CONFIG%DESTRUCT(EOS,PROP) !EOS & PROP ARE DESTRUCTED
END PROGRAM CTFS3D   