MODULE POSTVARIABLE_MODULE
  USE CONFIG_MODULE
  USE EOS_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_VARIABLE
  
  TYPE T_DOMAIN
    INTEGER :: RANK,IMAX,JMAX,KMAX
    REAL(8), DIMENSION(:,:,:,:), ALLOCATABLE :: PV,TV,DV
  END TYPE T_DOMAIN
  
  TYPE T_SOLUTION
    INTEGER :: SIZE,NPS,NTS
    TYPE(T_DOMAIN), DIMENSION(:), ALLOCATABLE :: DOMAIN
  END TYPE T_SOLUTION
  
  TYPE T_VARIABLE
    PRIVATE
    INTEGER :: NPV,NTV,NDV,NSOLUTION
    TYPE(T_SOLUTION), DIMENSION(:), ALLOCATABLE :: SOLUTION
    CONTAINS
      PROCEDURE :: CONSTRUCT
      PROCEDURE :: DESTRUCT
      PROCEDURE :: GETNPS
      PROCEDURE :: GETNTS
      PROCEDURE :: GETNPV
      PROCEDURE :: GETNTV
      PROCEDURE :: GETNDV
      PROCEDURE :: GETNSOLUTION
      PROCEDURE :: GETPV
      PROCEDURE :: GETTV
      PROCEDURE :: GETDV
      PROCEDURE :: GETSIZE
      PROCEDURE :: GETRANK
      PROCEDURE :: GETIMAX
      PROCEDURE :: GETJMAX
      PROCEDURE :: GETKMAX
  END TYPE T_VARIABLE

  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CONSTRUCT(VARIABLE,CONFIG,EOS,ISTART,IEND,NSOLUTION)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(OUT) :: VARIABLE
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_EOS), INTENT(IN) :: EOS
      INTEGER, INTENT(IN) :: ISTART,IEND,NSOLUTION
      CHARACTER(7) :: ITER_TAG
      REAL(8) :: VAR
      INTEGER :: I,J,K,N,M,L,O,IO,NQQ,ITER
      
      SELECT CASE(CONFIG%GETITURB())
      CASE(-3)
        VARIABLE%NPV = 7
        VARIABLE%NTV = 0  
      CASE(-2)
        VARIABLE%NPV = 7
        VARIABLE%NTV = 2      
      CASE(-1,0)
        VARIABLE%NPV = 9
        VARIABLE%NTV = 3      
      END SELECT
      VARIABLE%NDV = 18

      VARIABLE%NSOLUTION = NSOLUTION
      
      IF(MOD((IEND-ISTART)/CONFIG%GETNEXPORT()+1,VARIABLE%NSOLUTION).NE.0) THEN
        WRITE(*,*) 'INVALID NSOLUTION'
        PAUSE
      ELSE
        ITER = ((IEND-ISTART)/CONFIG%GETNEXPORT()+1)/VARIABLE%NSOLUTION
      END IF
      
      ALLOCATE(VARIABLE%SOLUTION(VARIABLE%NSOLUTION))
      
      DO L=1,VARIABLE%NSOLUTION
        IF(CONFIG%GETNSTEADY().EQ.1) THEN
          WRITE(ITER_TAG,'(I4.4)') ISTART+ITER*CONFIG%GETNEXPORT()*(L-1)
        ELSE
          WRITE(ITER_TAG,'(I7.7)') ISTART+ITER*CONFIG%GETNEXPORT()*(L-1)
        END IF
        
        OPEN(NEWUNIT=IO,FILE='./OUT_'//TRIM(ITER_TAG)//'.DAT',STATUS='OLD',ACTION='READ',FORM='UNFORMATTED',SHARED)
        READ(IO) VARIABLE%SOLUTION(L)%SIZE,VARIABLE%SOLUTION(L)%NPS,VARIABLE%SOLUTION(L)%NTS,NQQ
        
        ALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(0:VARIABLE%SOLUTION(L)%SIZE-1))
        
        DO M=0,VARIABLE%SOLUTION(L)%SIZE-1
          READ(IO) VARIABLE%SOLUTION(L)%DOMAIN(M)%RANK,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX
          
          ALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(VARIABLE%NPV,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX))
          ALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%DV(VARIABLE%NDV,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX))
          ALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%TV(VARIABLE%NTV,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX))
          
          READ(IO) ((((VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(N,I,J,K),N=1,VARIABLE%NPV),I=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX),J=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX),K=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX)
          READ(IO) ((((VARIABLE%SOLUTION(L)%DOMAIN(M)%TV(N,I,J,K),N=1,VARIABLE%NTV),I=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX),J=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX),K=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX)
          READ(IO) (((((VAR,O=1,NQQ),N=1,VARIABLE%NPV),I=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX),J=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX),K=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX)
          
          DO K=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX
            DO J=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX
              DO I=2,VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX
                CALL EOS%DETEOS(VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(1,I,J,K),VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(5,I,J,K),VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(6,I,J,K),VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(7,I,J,K) &
                                ,VARIABLE%SOLUTION(L)%DOMAIN(M)%DV(:,I,J,K)) 
              END DO
            END DO
          END DO
        END DO
        
        CLOSE(IO)
      END DO
  
    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE DESTRUCT(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      INTEGER :: L,M
      
      DO L=1,VARIABLE%NSOLUTION
        DO M=0,VARIABLE%SOLUTION(L)%SIZE-1
          DEALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%PV)
          DEALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%DV)
          DEALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN(M)%TV)
        END DO
        DEALLOCATE(VARIABLE%SOLUTION(L)%DOMAIN)
      END DO
      
      DEALLOCATE(VARIABLE%SOLUTION)
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNPS(VARIABLE,L)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L
      INTEGER :: GETNPS
      
      GETNPS = VARIABLE%SOLUTION(L)%NPS
    END FUNCTION GETNPS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNTS(VARIABLE,L)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L
      INTEGER :: GETNTS
      
      GETNTS = VARIABLE%SOLUTION(L)%NTS
    END FUNCTION GETNTS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNPV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNPV
      
      GETNPV = VARIABLE%NPV
      
    END FUNCTION GETNPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNTV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNTV
      
      GETNTV = VARIABLE%NTV
      
    END FUNCTION GETNTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNDV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNDV
      
      GETNDV = VARIABLE%NDV
      
    END FUNCTION GETNDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNSOLUTION(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNSOLUTION
      
      GETNSOLUTION = VARIABLE%NSOLUTION
      
    END FUNCTION GETNSOLUTION
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETPV(VARIABLE,L,M,N,I,J,K)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M,N,I,J,K
      REAL(8) :: GETPV
      
      GETPV = VARIABLE%SOLUTION(L)%DOMAIN(M)%PV(N,I,J,K)
    END FUNCTION GETPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETTV(VARIABLE,L,M,N,I,J,K)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M,N,I,J,K
      REAL(8) :: GETTV
      
      GETTV = VARIABLE%SOLUTION(L)%DOMAIN(M)%TV(N,I,J,K)
    END FUNCTION GETTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETDV(VARIABLE,L,M,N,I,J,K)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M,N,I,J,K
      REAL(8) :: GETDV
      
      GETDV = VARIABLE%SOLUTION(L)%DOMAIN(M)%DV(N,I,J,K)
    END FUNCTION GETDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETSIZE(VARIABLE,L)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L
      INTEGER :: GETSIZE
      GETSIZE = VARIABLE%SOLUTION(L)%SIZE
    END FUNCTION GETSIZE
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETRANK(VARIABLE,L,M)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M
      INTEGER :: GETRANK
      
      GETRANK = VARIABLE%SOLUTION(L)%DOMAIN(M)%RANK
    END FUNCTION GETRANK
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETIMAX(VARIABLE,L,M)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M
      INTEGER :: GETIMAX
      
      GETIMAX = VARIABLE%SOLUTION(L)%DOMAIN(M)%IMAX
    END FUNCTION GETIMAX
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETJMAX(VARIABLE,L,M)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M
      INTEGER :: GETJMAX
      
      GETJMAX = VARIABLE%SOLUTION(L)%DOMAIN(M)%JMAX
    END FUNCTION GETJMAX
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETKMAX(VARIABLE,L,M)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: L,M
      INTEGER :: GETKMAX
      
      GETKMAX = VARIABLE%SOLUTION(L)%DOMAIN(M)%KMAX
    END FUNCTION GETKMAX
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE POSTVARIABLE_MODULE