PROGRAM POSTCONVERTER
  USE CONFIG_MODULE
  USE GRID_MODULE
  USE EOS_MODULE
  USE PROP_MODULE
  USE POSTVARIABLE_MODULE
  USE DATAWRITING_MODULE
  
  IMPLICIT NONE
  TYPE(T_CONFIG) :: CONFIG
  TYPE(T_GRID) :: GRID
  TYPE(T_EOS) :: EOS
  TYPE(T_PROP) :: PROP
  TYPE(T_VARIABLE) :: VARIABLE
  TYPE(T_DATAWRITING) :: DATAWRITING
  
  INTEGER :: IO,ISTART,IEND,NSOLUTION
  
  OPEN(NEWUNIT=IO,FILE='./INPUT_POST.INP',STATUS='OLD',ACTION='READ')
  READ(IO,*); READ(IO,*) ISTART
  READ(IO,*); READ(IO,*) IEND
  READ(IO,*); READ(IO,*) NSOLUTION
  CLOSE(IO)
      
  CALL CONFIG%CONSTRUCT(EOS,PROP) !EOS & PROP ARE ALSO CONSTRUCTED
  CALL GRID%CONSTRUCT(CONFIG)
  CALL VARIABLE%CONSTRUCT(CONFIG,EOS,ISTART,IEND,NSOLUTION)
      
  CALL DATAWRITING%CGNSWRITING(CONFIG,VARIABLE)
  CALL DATAWRITING%CL_WRITING(CONFIG,GRID,VARIABLE)
  
  CALL VARIABLE%DESTRUCT()
  CALL GRID%DESTRUCT()
  CALL CONFIG%DESTRUCT(EOS,PROP) !EOS & PROP ARE DESTRUCTED
END PROGRAM POSTCONVERTER