MODULE VARIABLE_MODULE
  USE CONFIG_MODULE
  USE GRID_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_VARIABLE
  
  TYPE T_VARIABLE
    PRIVATE
    INTEGER :: NPV,NDV,NTV,NQQ
    REAL(8), DIMENSION(:,:,:), ALLOCATABLE :: PV   ! P,U,V,T,Y1,Y2,K,O
    REAL(8), DIMENSION(:,:,:), ALLOCATABLE :: DV   ! RHO,H,RHOL,RHOV,RHOG,SND2,DRDP,DRDT,DRDY1,DRDY2,DHDP,DHDT,DHDY1,DHDY2,DRDPV,DRDTV,DRDPL,DRDTL
    REAL(8), DIMENSION(:,:,:), ALLOCATABLE :: TV   ! VIS,COND,EMUT
    REAL(8), DIMENSION(:,:,:,:), ALLOCATABLE :: QQ ! UNSTEADY N-1,N-2 CONSERVATIVE VARIABLE
    CONTAINS
      PROCEDURE :: CONSTRUCT
      PROCEDURE :: DESTRUCT
      PROCEDURE :: GETNPV
      PROCEDURE :: GETNDV
      PROCEDURE :: GETNTV
      PROCEDURE :: GETNQQ
      PROCEDURE :: GETPV
      PROCEDURE :: GETDV
      PROCEDURE :: GETTV
      PROCEDURE :: GETQQ
      PROCEDURE :: SETPV
      PROCEDURE :: SETDV
      PROCEDURE :: SETTV
      PROCEDURE :: SETQQ
  END TYPE T_VARIABLE
  
  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE CONSTRUCT(VARIABLE,CONFIG,GRID)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(OUT) :: VARIABLE
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_GRID), INTENT(IN) :: GRID
          
      SELECT CASE(CONFIG%GETITURB())
      CASE(-3)
        VARIABLE%NPV = 6
        VARIABLE%NTV = 0  
      CASE(-2)
        VARIABLE%NPV = 6
        VARIABLE%NTV = 2      
      CASE(-1,0)
        VARIABLE%NPV = 8
        VARIABLE%NTV = 3      
      END SELECT
      VARIABLE%NDV = 18
      SELECT CASE(CONFIG%GETNSTEADY())
      CASE(0)
        VARIABLE%NQQ = 0
      CASE(1)
        VARIABLE%NQQ = 2
      END SELECT      
      ALLOCATE(VARIABLE%PV(VARIABLE%NPV,-1:GRID%GETIMAX()+3,-1:GRID%GETJMAX()+3))
      ALLOCATE(VARIABLE%DV(VARIABLE%NDV,-1:GRID%GETIMAX()+3,-1:GRID%GETJMAX()+3))
      ALLOCATE(VARIABLE%TV(VARIABLE%NTV,-1:GRID%GETIMAX()+3,-1:GRID%GETJMAX()+3))
      ALLOCATE(VARIABLE%QQ(VARIABLE%NQQ,VARIABLE%NPV,2:GRID%GETIMAX(),2:GRID%GETJMAX()))

      
    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE DESTRUCT(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
          
      IF(ALLOCATED(VARIABLE%PV)) DEALLOCATE(VARIABLE%PV)
      IF(ALLOCATED(VARIABLE%DV)) DEALLOCATE(VARIABLE%DV)
      IF(ALLOCATED(VARIABLE%TV)) DEALLOCATE(VARIABLE%TV)
      IF(ALLOCATED(VARIABLE%QQ)) DEALLOCATE(VARIABLE%QQ)
      
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNPV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNPV
      
      GETNPV = VARIABLE%NPV
      
    END FUNCTION GETNPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNDV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNDV
      
      GETNDV = VARIABLE%NDV
      
    END FUNCTION GETNDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNTV(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNTV
      
      GETNTV = VARIABLE%NTV
      
    END FUNCTION GETNTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETNQQ(VARIABLE)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER :: GETNQQ
      
      GETNQQ = VARIABLE%NQQ
      
    END FUNCTION GETNQQ
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETPV(VARIABLE,I,J)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: I,J
      REAL(8) :: GETPV(VARIABLE%NPV)
      
      GETPV = VARIABLE%PV(:,I,J)
      
    END FUNCTION GETPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETDV(VARIABLE,I,J)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: I,J
      REAL(8) :: GETDV(VARIABLE%NDV)
      
      GETDV = VARIABLE%DV(:,I,J)
      
    END FUNCTION GETDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETTV(VARIABLE,I,J)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: I,J
      REAL(8) :: GETTV(VARIABLE%NTV)
      
      GETTV = VARIABLE%TV(:,I,J)
      
    END FUNCTION GETTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION GETQQ(VARIABLE,N,I,J)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(IN) :: VARIABLE
      INTEGER, INTENT(IN) :: I,J,N
      REAL(8) :: GETQQ(VARIABLE%NPV)
      
      GETQQ = VARIABLE%QQ(N,:,I,J)
      
    END FUNCTION GETQQ
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETPV(VARIABLE,N,I,J,VAR)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      INTEGER, INTENT(IN) :: N,I,J
      REAL(8), INTENT(IN) :: VAR
      
      VARIABLE%PV(N,I,J) = VAR
      
    END SUBROUTINE SETPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETDV(VARIABLE,N,I,J,VAR)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      INTEGER, INTENT(IN) :: N,I,J
      REAL(8), INTENT(IN) :: VAR
      
      VARIABLE%DV(N,I,J) = VAR
      
    END SUBROUTINE SETDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETTV(VARIABLE,N,I,J,VAR)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      INTEGER, INTENT(IN) :: N,I,J
      REAL(8), INTENT(IN) :: VAR
      
      VARIABLE%TV(N,I,J) = VAR
      
    END SUBROUTINE SETTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETQQ(VARIABLE,N,I,J,VAR)
      IMPLICIT NONE
      CLASS(T_VARIABLE), INTENT(INOUT) :: VARIABLE
      INTEGER, INTENT(IN) :: N,I,J
      REAL(8), INTENT(IN) :: VAR(VARIABLE%NPV)
      
      VARIABLE%QQ(N,:,I,J) = VAR
      
    END SUBROUTINE SETQQ
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE VARIABLE_MODULE