MODULE VSFLUX_MODULE
  USE CONFIG_MODULE
  USE GRID_MODULE
  USE VARIABLE_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: T_VSFLUX,T_VSFLUX_LAMINAR,T_VSFLUX_TURBULENT

  TYPE, ABSTRACT :: T_VSFLUX
    PRIVATE
    INTEGER :: NPV,NTV,NGRD,NDV
    REAL(8) :: TDK1,TDK2,TDO1,TDO2
    REAL(8) :: PR_T
    REAL(8), POINTER :: PV(:,:)
    REAL(8), POINTER :: NX(:)
    REAL(8), POINTER :: EX1(:),EX2(:),EX3(:),EX4(:)
    REAL(8), POINTER :: TX1(:),TX2(:),TX3(:),TX4(:)
    REAL(8), POINTER :: GRDL(:),GRDR(:)
    REAL(8), POINTER :: DVL(:),DVR(:)
    REAL(8), POINTER :: TVL(:),TVR(:)
    PROCEDURE(P_CALBIGF), POINTER :: CALBIGF
    CONTAINS
      PROCEDURE :: CONSTRUCT  
      PROCEDURE :: DESTRUCT
      PROCEDURE :: SETNORM    ! (NX,EX1,EX2,EX3,EX4,TX1,TX2,TX3,TX4)
      PROCEDURE :: SETGRD     ! (GRDL,GRDR) VOL,XCEN,YCEN,ZCEN,YDNS
      PROCEDURE :: SETPV      ! (PV(14,NPV)) P,U,V,W,T,Y1,Y2,K,O
      PROCEDURE :: SETDV      ! (DVL,DVR) RHO,H,RHOL,RHOV,RHOG,SND2,DRDP,DRDT,DRDY1,DRDY2,DHDP,DHDT,DHDY1,DHDY2,DRDPV,DRDTV,DRDPL,DRDTL
      PROCEDURE :: SETTV      ! (TVL,TVR) VIS,COND,EMUT
      PROCEDURE(P_CALFLUX), DEFERRED :: CALFLUX
  END TYPE T_VSFLUX
 
  ABSTRACT INTERFACE
    SUBROUTINE P_CALFLUX(VSFLUX,FX)
      IMPORT T_VSFLUX
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(OUT) :: FX(VSFLUX%NPV)
    END SUBROUTINE P_CALFLUX
  END INTERFACE
  
  TYPE, EXTENDS(T_VSFLUX) :: T_VSFLUX_LAMINAR
    CONTAINS
    PROCEDURE :: CALFLUX => VSFLUX_LAMINAR
  END TYPE T_VSFLUX_LAMINAR
  
  TYPE, EXTENDS(T_VSFLUX) :: T_VSFLUX_TURBULENT
    CONTAINS
    PROCEDURE :: CALFLUX => VSFLUX_TURBULENT
  END TYPE T_VSFLUX_TURBULENT
  
  INTERFACE
    FUNCTION P_CALBIGF(VSFLUX,PKW) RESULT(BIGF)
      IMPORT T_VSFLUX
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(IN) :: PKW
      REAL(8) :: BIGF
    END FUNCTION P_CALBIGF
  END INTERFACE
  
  CONTAINS
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    SUBROUTINE CONSTRUCT(VSFLUX,CONFIG,GRID,VARIABLE)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(OUT) :: VSFLUX
      TYPE(T_CONFIG), INTENT(IN) :: CONFIG
      TYPE(T_GRID), INTENT(IN) :: GRID
      TYPE(T_VARIABLE), INTENT(IN) :: VARIABLE
      
      SELECT CASE(CONFIG%GETITURB())
      CASE(-1)
        VSFLUX%TDK1 = 0.D0
        VSFLUX%TDK2 = 1.D0
        VSFLUX%TDO1 = 0.D0
        VSFLUX%TDO2 = 1.D0/1.3D0
        VSFLUX%CALBIGF => KEPSILON
        VSFLUX%PR_T=0.9D0
      CASE(0)
        VSFLUX%TDK1 = 0.85D0
        VSFLUX%TDK2 = 1.D0
        VSFLUX%TDO1 = 0.5D0
        VSFLUX%TDO2 = 0.856D0
        VSFLUX%CALBIGF => KWSST
        VSFLUX%PR_T=0.9D0
      CASE(-2)
        VSFLUX%TDK1 = 0.D0
        VSFLUX%TDK2 = 0.D0
        VSFLUX%TDO1 = 0.D0
        VSFLUX%TDO2 = 0.D0
        VSFLUX%CALBIGF => NULL()
        VSFLUX%PR_T=0.D0
      END SELECT
      
      VSFLUX%NGRD = GRID%GETNGRD()
      
      VSFLUX%NPV = VARIABLE%GETNPV()
      VSFLUX%NDV = VARIABLE%GETNDV()
      VSFLUX%NTV = VARIABLE%GETNTV()
      
    END SUBROUTINE CONSTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC    
    SUBROUTINE DESTRUCT(VSFLUX)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX

      IF(ASSOCIATED(VSFLUX%NX))      NULLIFY(VSFLUX%NX)
      IF(ASSOCIATED(VSFLUX%EX1))     NULLIFY(VSFLUX%EX1)    
      IF(ASSOCIATED(VSFLUX%EX2))     NULLIFY(VSFLUX%EX2)    
      IF(ASSOCIATED(VSFLUX%EX3))     NULLIFY(VSFLUX%EX3)    
      IF(ASSOCIATED(VSFLUX%EX4))     NULLIFY(VSFLUX%EX4)
      IF(ASSOCIATED(VSFLUX%TX1))     NULLIFY(VSFLUX%TX1)    
      IF(ASSOCIATED(VSFLUX%TX2))     NULLIFY(VSFLUX%TX2)    
      IF(ASSOCIATED(VSFLUX%TX3))     NULLIFY(VSFLUX%TX3)    
      IF(ASSOCIATED(VSFLUX%TX4))     NULLIFY(VSFLUX%TX4)
      IF(ASSOCIATED(VSFLUX%GRDL))    NULLIFY(VSFLUX%GRDL)   
      IF(ASSOCIATED(VSFLUX%GRDR))    NULLIFY(VSFLUX%GRDR) 
      IF(ASSOCIATED(VSFLUX%PV))      NULLIFY(VSFLUX%PV)     
      IF(ASSOCIATED(VSFLUX%DVL))     NULLIFY(VSFLUX%DVL)    
      IF(ASSOCIATED(VSFLUX%DVR))     NULLIFY(VSFLUX%DVR)     
      IF(ASSOCIATED(VSFLUX%TVL))     NULLIFY(VSFLUX%TVL)    
      IF(ASSOCIATED(VSFLUX%TVR))     NULLIFY(VSFLUX%TVR)    
      IF(ASSOCIATED(VSFLUX%CALBIGF)) NULLIFY(VSFLUX%CALBIGF)
      
    END SUBROUTINE DESTRUCT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETNORM(VSFLUX,NX,EX1,EX2,EX3,EX4,TX1,TX2,TX3,TX4)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX
      REAL(8), INTENT(IN), TARGET :: NX(3),EX1(3),EX2(3),EX3(3),EX4(3),TX1(3),TX2(3),TX3(3),TX4(3)
      
      VSFLUX%NX  => NX
      VSFLUX%EX1 => EX1
      VSFLUX%EX2 => EX2
      VSFLUX%EX3 => EX3
      VSFLUX%EX4 => EX4
      VSFLUX%TX1 => TX1
      VSFLUX%TX2 => TX2
      VSFLUX%TX3 => TX3
      VSFLUX%TX4 => TX4    
    END SUBROUTINE SETNORM 
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETGRD(VSFLUX,GRDL,GRDR)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX
      REAL(8), INTENT(IN), TARGET :: GRDL(VSFLUX%NGRD),GRDR(VSFLUX%NGRD)
      
      VSFLUX%GRDL => GRDL
      VSFLUX%GRDR => GRDR
      
    END SUBROUTINE SETGRD
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETPV(VSFLUX,PV)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX
      REAL(8), INTENT(IN), TARGET :: PV(38,VSFLUX%NPV) ! PV(19,:)~PV(38,:) ARE NOT USED !! PLZ CHECK
      
      VSFLUX%PV => PV
      
    END SUBROUTINE SETPV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC  
    SUBROUTINE SETDV(VSFLUX,DVL,DVR)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX
      REAL(8), INTENT(IN), TARGET :: DVL(VSFLUX%NDV),DVR(VSFLUX%NDV)
      
      VSFLUX%DVL => DVL
      VSFLUX%DVR => DVR
      
    END SUBROUTINE SETDV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE SETTV(VSFLUX,TVL,TVR)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(INOUT) :: VSFLUX
      REAL(8), INTENT(IN), TARGET :: TVL(VSFLUX%NTV),TVR(VSFLUX%NTV)
      
      VSFLUX%TVL => TVL
      VSFLUX%TVR => TVR
      
    END SUBROUTINE SETTV
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    SUBROUTINE VSFLUX_LAMINAR(VSFLUX,FX)
      IMPLICIT NONE
      CLASS(T_VSFLUX_LAMINAR), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(OUT) :: FX(VSFLUX%NPV)
      REAL(8) :: TX,TY,TZ,EX,EY,EZ
      REAL(8) :: VOL,VIS,CON,UC,VC,WC
      REAL(8) :: DUDN,DVDN,DWDN,DTDN
      REAL(8) :: DUDE,DVDE,DWDE,DTDE
      REAL(8) :: DUDT,DVDT,DWDT,DTDT
      REAL(8) :: DUDX,DUDY,DUDZ,DVDX,DVDY,DVDZ,DWDX,DWDY,DWDZ,DTDX,DTDY,DTDZ
      REAL(8) :: TAUXX,TAUYY,TAUZZ,TAUXY,TAUXZ,TAUYZ
      

      EX = 0.25D0*(VSFLUX%EX1(1)+VSFLUX%EX2(1)+VSFLUX%EX3(1)+VSFLUX%EX4(1)) 
      EY = 0.25D0*(VSFLUX%EX1(2)+VSFLUX%EX2(2)+VSFLUX%EX3(2)+VSFLUX%EX4(2))
      EZ = 0.25D0*(VSFLUX%EX1(3)+VSFLUX%EX2(3)+VSFLUX%EX3(3)+VSFLUX%EX4(3))
      
      TX = 0.25D0*(VSFLUX%TX1(1)+VSFLUX%TX2(1)+VSFLUX%TX3(1)+VSFLUX%TX4(1)) 
      TY = 0.25D0*(VSFLUX%TX1(2)+VSFLUX%TX2(2)+VSFLUX%TX3(2)+VSFLUX%TX4(2))
      TZ = 0.25D0*(VSFLUX%TX1(3)+VSFLUX%TX2(3)+VSFLUX%TX3(3)+VSFLUX%TX4(3))
      
      VOL  = 0.5D0*(VSFLUX%GRDL(1) + VSFLUX%GRDR(1))
      VIS  = 0.5D0*(VSFLUX%TVL(1) + VSFLUX%TVR(1))
      CON  = 0.5D0*(VSFLUX%TVL(2) + VSFLUX%TVR(2))
      UC   = 0.5D0*(VSFLUX%PV(9,2) + VSFLUX%PV(10,2))
      VC   = 0.5D0*(VSFLUX%PV(9,3) + VSFLUX%PV(10,3))
      WC   = 0.5D0*(VSFLUX%PV(9,4) + VSFLUX%PV(10,4))
      
      DUDN = VSFLUX%PV(10,2) - VSFLUX%PV(9,2)
      DVDN = VSFLUX%PV(10,3) - VSFLUX%PV(9,3)
      DWDN = VSFLUX%PV(10,4) - VSFLUX%PV(9,4)
      DTDN = VSFLUX%PV(10,5) - VSFLUX%PV(9,5)
      
      DUDE = 0.0625D0*(- VSFLUX%PV(1,2)  - VSFLUX%PV(2,2)  + VSFLUX%PV(5,2)  + VSFLUX%PV(6,2)   &
               + 2.D0*(- VSFLUX%PV(7,2)  - VSFLUX%PV(8,2)  + VSFLUX%PV(11,2) + VSFLUX%PV(12,2)) &
                       - VSFLUX%PV(13,2) - VSFLUX%PV(14,2) + VSFLUX%PV(17,2) + VSFLUX%PV(18,2))
      DVDE = 0.0625D0*(- VSFLUX%PV(1,3)  - VSFLUX%PV(2,3)  + VSFLUX%PV(5,3)  + VSFLUX%PV(6,3)   &
               + 2.D0*(- VSFLUX%PV(7,3)  - VSFLUX%PV(8,3)  + VSFLUX%PV(11,3) + VSFLUX%PV(12,3)) &
                       - VSFLUX%PV(13,3) - VSFLUX%PV(14,3) + VSFLUX%PV(17,3) + VSFLUX%PV(18,3))
      DWDE = 0.0625D0*(- VSFLUX%PV(1,4)  - VSFLUX%PV(2,4)  + VSFLUX%PV(5,4)  + VSFLUX%PV(6,4)   &
               + 2.D0*(- VSFLUX%PV(7,4)  - VSFLUX%PV(8,4)  + VSFLUX%PV(11,4) + VSFLUX%PV(12,4)) &
                       - VSFLUX%PV(13,4) - VSFLUX%PV(14,4) + VSFLUX%PV(17,4) + VSFLUX%PV(18,4))
      DTDE = 0.0625D0*(- VSFLUX%PV(1,5)  - VSFLUX%PV(2,5)  + VSFLUX%PV(5,5)  + VSFLUX%PV(6,5)   &
               + 2.D0*(- VSFLUX%PV(7,5)  - VSFLUX%PV(8,5)  + VSFLUX%PV(11,5) + VSFLUX%PV(12,5)) &
                       - VSFLUX%PV(13,5) - VSFLUX%PV(14,5) + VSFLUX%PV(17,5) + VSFLUX%PV(18,5))
               
      DUDT = 0.0625D0*(- VSFLUX%PV(1,2)  - VSFLUX%PV(2,2)  + VSFLUX%PV(13,2) + VSFLUX%PV(14,2)   &
               + 2.D0*(- VSFLUX%PV(3,2)  - VSFLUX%PV(4,2)  + VSFLUX%PV(15,2) + VSFLUX%PV(16,2))  &
                       - VSFLUX%PV(5,2)  - VSFLUX%PV(6,2)  + VSFLUX%PV(17,2) + VSFLUX%PV(18,2))
      DVDT = 0.0625D0*(- VSFLUX%PV(1,3)  - VSFLUX%PV(2,3)  + VSFLUX%PV(13,3) + VSFLUX%PV(14,3)   &
               + 2.D0*(- VSFLUX%PV(3,3)  - VSFLUX%PV(4,3)  + VSFLUX%PV(15,3) + VSFLUX%PV(16,3))  &
                       - VSFLUX%PV(5,3)  - VSFLUX%PV(6,3)  + VSFLUX%PV(17,3) + VSFLUX%PV(18,3))
      DWDT = 0.0625D0*(- VSFLUX%PV(1,4)  - VSFLUX%PV(2,4)  + VSFLUX%PV(13,4) + VSFLUX%PV(14,4)   &
               + 2.D0*(- VSFLUX%PV(3,4)  - VSFLUX%PV(4,4)  + VSFLUX%PV(15,4) + VSFLUX%PV(16,4))  &
                       - VSFLUX%PV(5,4)  - VSFLUX%PV(6,4)  + VSFLUX%PV(17,4) + VSFLUX%PV(18,4))
      DTDT = 0.0625D0*(- VSFLUX%PV(1,5)  - VSFLUX%PV(2,5)  + VSFLUX%PV(13,5) + VSFLUX%PV(14,5)   &
               + 2.D0*(- VSFLUX%PV(3,5)  - VSFLUX%PV(4,5)  + VSFLUX%PV(15,5) + VSFLUX%PV(16,5))  &
                       - VSFLUX%PV(5,5)  - VSFLUX%PV(6,5)  + VSFLUX%PV(17,5) + VSFLUX%PV(18,5))
      
      DUDX = (DUDN*VSFLUX%NX(1)+DUDE*EX+DUDT*TX)/VOL
      DVDX = (DVDN*VSFLUX%NX(1)+DVDE*EX+DVDT*TX)/VOL
      DWDX = (DWDN*VSFLUX%NX(1)+DWDE*EX+DWDT*TX)/VOL
      DTDX = (DTDN*VSFLUX%NX(1)+DTDE*EX+DTDT*TX)/VOL
 
      DUDY = (DUDN*VSFLUX%NX(2)+DUDE*EY+DUDT*TY)/VOL
      DVDY = (DVDN*VSFLUX%NX(2)+DVDE*EY+DVDT*TY)/VOL
      DWDY = (DWDN*VSFLUX%NX(2)+DWDE*EY+DWDT*TY)/VOL
      DTDY = (DTDN*VSFLUX%NX(2)+DTDE*EY+DTDT*TY)/VOL

      DUDZ = (DUDN*VSFLUX%NX(3)+DUDE*EZ+DUDT*TZ)/VOL
      DVDZ = (DVDN*VSFLUX%NX(3)+DVDE*EZ+DVDT*TZ)/VOL
      DWDZ = (DWDN*VSFLUX%NX(3)+DWDE*EZ+DWDT*TZ)/VOL
      DTDZ = (DTDN*VSFLUX%NX(3)+DTDE*EZ+DTDT*TZ)/VOL
      
      TAUXX = VIS*(2.D0*DUDX -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUYY = VIS*(2.D0*DVDY -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUZZ = VIS*(2.D0*DWDZ -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUXY = VIS*(DUDY+DVDX)
      TAUXZ = VIS*(DUDZ+DWDX)
      TAUYZ = VIS*(DVDZ+DWDY)
      
      FX(1) = 0.D0
      FX(2) = (TAUXX*VSFLUX%NX(1)+TAUXY*VSFLUX%NX(2)+TAUXZ*VSFLUX%NX(3))
      FX(3) = (TAUXY*VSFLUX%NX(1)+TAUYY*VSFLUX%NX(2)+TAUYZ*VSFLUX%NX(3))
      FX(4) = (TAUXZ*VSFLUX%NX(1)+TAUYZ*VSFLUX%NX(2)+TAUZZ*VSFLUX%NX(3))
      FX(5) = (VSFLUX%NX(1)*(UC*TAUXX+VC*TAUXY+WC*TAUXZ+CON*DTDX) &
            +  VSFLUX%NX(2)*(UC*TAUXY+VC*TAUYY+WC*TAUYZ+CON*DTDY) &
            +  VSFLUX%NX(3)*(UC*TAUXZ+VC*TAUYZ+WC*TAUZZ+CON*DTDZ) )
      FX(6) = 0.D0
      FX(7) = 0.D0

    END SUBROUTINE VSFLUX_LAMINAR
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 
    SUBROUTINE VSFLUX_TURBULENT(VSFLUX,FX)
      IMPLICIT NONE
      CLASS(T_VSFLUX_TURBULENT), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(OUT) :: FX(VSFLUX%NPV)
      REAL(8) :: TX,TY,TZ,EX,EY,EZ
      REAL(8) :: VOL,VIS,CON,EMUT,TCON,BIGF,UC,VC,WC
      REAL(8) :: DUDN,DVDN,DWDN,DTDN,DKDN,DODN
      REAL(8) :: DUDE,DVDE,DWDE,DTDE,DKDE,DODE
      REAL(8) :: DUDT,DVDT,DWDT,DTDT,DKDT,DODT
      REAL(8) :: DUDX,DUDY,DUDZ,DVDX,DVDY,DVDZ,DWDX,DWDY,DWDZ,DTDX,DTDY,DTDZ
      REAL(8) :: DKDX,DKDY,DKDZ,DODX,DODY,DODZ
      REAL(8) :: TAUXX,TAUYY,TAUZZ,TAUXY,TAUXZ,TAUYZ
      REAL(8) :: TDK,TDO
      
      EX = 0.25D0*(VSFLUX%EX1(1)+VSFLUX%EX2(1)+VSFLUX%EX3(1)+VSFLUX%EX4(1)) 
      EY = 0.25D0*(VSFLUX%EX1(2)+VSFLUX%EX2(2)+VSFLUX%EX3(2)+VSFLUX%EX4(2))
      EZ = 0.25D0*(VSFLUX%EX1(3)+VSFLUX%EX2(3)+VSFLUX%EX3(3)+VSFLUX%EX4(3))
      
      TX = 0.25D0*(VSFLUX%TX1(1)+VSFLUX%TX2(1)+VSFLUX%TX3(1)+VSFLUX%TX4(1)) 
      TY = 0.25D0*(VSFLUX%TX1(2)+VSFLUX%TX2(2)+VSFLUX%TX3(2)+VSFLUX%TX4(2))
      TZ = 0.25D0*(VSFLUX%TX1(3)+VSFLUX%TX2(3)+VSFLUX%TX3(3)+VSFLUX%TX4(3))
      
      VOL  = 0.5D0*(VSFLUX%GRDL(1) + VSFLUX%GRDR(1))
      VIS  = 0.5D0*(VSFLUX%TVL(1) + VSFLUX%TVR(1))
      CON  = 0.5D0*(VSFLUX%TVL(2) + VSFLUX%TVR(2))
      EMUT = 0.5D0*(VSFLUX%TVL(3) + VSFLUX%TVR(3))
      TCON = 0.5D0*(VSFLUX%TVL(3)*VSFLUX%DVL(12)+ VSFLUX%TVR(3)*VSFLUX%DVR(12))/VSFLUX%PR_T
      UC   = 0.5D0*(VSFLUX%PV(9,2) + VSFLUX%PV(10,2))
      VC   = 0.5D0*(VSFLUX%PV(9,3) + VSFLUX%PV(10,3))
      WC   = 0.5D0*(VSFLUX%PV(9,4) + VSFLUX%PV(10,4))
      
      DUDN = VSFLUX%PV(10,2) - VSFLUX%PV(9,2)
      DVDN = VSFLUX%PV(10,3) - VSFLUX%PV(9,3)
      DWDN = VSFLUX%PV(10,4) - VSFLUX%PV(9,4)
      DTDN = VSFLUX%PV(10,5) - VSFLUX%PV(9,5)
      DKDN = VSFLUX%PV(10,8) - VSFLUX%PV(9,8)
      DODN = VSFLUX%PV(10,9) - VSFLUX%PV(9,9) 
      
      DUDE = 0.0625D0*(- VSFLUX%PV(1,2)  - VSFLUX%PV(2,2)  + VSFLUX%PV(5,2)  + VSFLUX%PV(6,2)   &
               + 2.D0*(- VSFLUX%PV(7,2)  - VSFLUX%PV(8,2)  + VSFLUX%PV(11,2) + VSFLUX%PV(12,2)) &
                       - VSFLUX%PV(13,2) - VSFLUX%PV(14,2) + VSFLUX%PV(17,2) + VSFLUX%PV(18,2))
      DVDE = 0.0625D0*(- VSFLUX%PV(1,3)  - VSFLUX%PV(2,3)  + VSFLUX%PV(5,3)  + VSFLUX%PV(6,3)   &
               + 2.D0*(- VSFLUX%PV(7,3)  - VSFLUX%PV(8,3)  + VSFLUX%PV(11,3) + VSFLUX%PV(12,3)) &
                       - VSFLUX%PV(13,3) - VSFLUX%PV(14,3) + VSFLUX%PV(17,3) + VSFLUX%PV(18,3))
      DWDE = 0.0625D0*(- VSFLUX%PV(1,4)  - VSFLUX%PV(2,4)  + VSFLUX%PV(5,4)  + VSFLUX%PV(6,4)   &
               + 2.D0*(- VSFLUX%PV(7,4)  - VSFLUX%PV(8,4)  + VSFLUX%PV(11,4) + VSFLUX%PV(12,4)) &
                       - VSFLUX%PV(13,4) - VSFLUX%PV(14,4) + VSFLUX%PV(17,4) + VSFLUX%PV(18,4))
      DTDE = 0.0625D0*(- VSFLUX%PV(1,5)  - VSFLUX%PV(2,5)  + VSFLUX%PV(5,5)  + VSFLUX%PV(6,5)   &
               + 2.D0*(- VSFLUX%PV(7,5)  - VSFLUX%PV(8,5)  + VSFLUX%PV(11,5) + VSFLUX%PV(12,5)) &
                       - VSFLUX%PV(13,5) - VSFLUX%PV(14,5) + VSFLUX%PV(17,5) + VSFLUX%PV(18,5))
      DKDE = 0.0625D0*(- VSFLUX%PV(1,8)  - VSFLUX%PV(2,8)  + VSFLUX%PV(5,8)  + VSFLUX%PV(6,8)   &
               + 2.D0*(- VSFLUX%PV(7,8)  - VSFLUX%PV(8,8)  + VSFLUX%PV(11,8) + VSFLUX%PV(12,8)) &
                       - VSFLUX%PV(13,8) - VSFLUX%PV(14,8) + VSFLUX%PV(17,8) + VSFLUX%PV(18,8))
      DODE = 0.0625D0*(- VSFLUX%PV(1,9)  - VSFLUX%PV(2,9)  + VSFLUX%PV(5,9)  + VSFLUX%PV(6,9)   &
               + 2.D0*(- VSFLUX%PV(7,9)  - VSFLUX%PV(8,9)  + VSFLUX%PV(11,9) + VSFLUX%PV(12,9)) &
                       - VSFLUX%PV(13,9) - VSFLUX%PV(14,9) + VSFLUX%PV(17,9) + VSFLUX%PV(18,9))
                       
      DUDT = 0.0625D0*(- VSFLUX%PV(1,2)  - VSFLUX%PV(2,2)  + VSFLUX%PV(13,2) + VSFLUX%PV(14,2)   &
               + 2.D0*(- VSFLUX%PV(3,2)  - VSFLUX%PV(4,2)  + VSFLUX%PV(15,2) + VSFLUX%PV(16,2))  &
                       - VSFLUX%PV(5,2)  - VSFLUX%PV(6,2)  + VSFLUX%PV(17,2) + VSFLUX%PV(18,2))
      DVDT = 0.0625D0*(- VSFLUX%PV(1,3)  - VSFLUX%PV(2,3)  + VSFLUX%PV(13,3) + VSFLUX%PV(14,3)   &
               + 2.D0*(- VSFLUX%PV(3,3)  - VSFLUX%PV(4,3)  + VSFLUX%PV(15,3) + VSFLUX%PV(16,3))  &
                       - VSFLUX%PV(5,3)  - VSFLUX%PV(6,3)  + VSFLUX%PV(17,3) + VSFLUX%PV(18,3))
      DWDT = 0.0625D0*(- VSFLUX%PV(1,4)  - VSFLUX%PV(2,4)  + VSFLUX%PV(13,4) + VSFLUX%PV(14,4)   &
               + 2.D0*(- VSFLUX%PV(3,4)  - VSFLUX%PV(4,4)  + VSFLUX%PV(15,4) + VSFLUX%PV(16,4))  &
                       - VSFLUX%PV(5,4)  - VSFLUX%PV(6,4)  + VSFLUX%PV(17,4) + VSFLUX%PV(18,4))
      DTDT = 0.0625D0*(- VSFLUX%PV(1,5)  - VSFLUX%PV(2,5)  + VSFLUX%PV(13,5) + VSFLUX%PV(14,5)   &
               + 2.D0*(- VSFLUX%PV(3,5)  - VSFLUX%PV(4,5)  + VSFLUX%PV(15,5) + VSFLUX%PV(16,5))  &
                       - VSFLUX%PV(5,5)  - VSFLUX%PV(6,5)  + VSFLUX%PV(17,5) + VSFLUX%PV(18,5))
      DKDT = 0.0625D0*(- VSFLUX%PV(1,8)  - VSFLUX%PV(2,8)  + VSFLUX%PV(13,8) + VSFLUX%PV(14,8)   &
               + 2.D0*(- VSFLUX%PV(3,8)  - VSFLUX%PV(4,8)  + VSFLUX%PV(15,8) + VSFLUX%PV(16,8))  &
                       - VSFLUX%PV(5,8)  - VSFLUX%PV(6,8)  + VSFLUX%PV(17,8) + VSFLUX%PV(18,8))
      DODT = 0.0625D0*(- VSFLUX%PV(1,9)  - VSFLUX%PV(2,9)  + VSFLUX%PV(13,9) + VSFLUX%PV(14,9)   &
               + 2.D0*(- VSFLUX%PV(3,9)  - VSFLUX%PV(4,9)  + VSFLUX%PV(15,9) + VSFLUX%PV(16,9))  &
                       - VSFLUX%PV(5,9)  - VSFLUX%PV(6,9)  + VSFLUX%PV(17,9) + VSFLUX%PV(18,9))

                       
      DUDX = (DUDN*VSFLUX%NX(1)+DUDE*EX+DUDT*TX)/VOL
      DVDX = (DVDN*VSFLUX%NX(1)+DVDE*EX+DVDT*TX)/VOL
      DWDX = (DWDN*VSFLUX%NX(1)+DWDE*EX+DWDT*TX)/VOL
      DTDX = (DTDN*VSFLUX%NX(1)+DTDE*EX+DTDT*TX)/VOL
      DKDX = (DKDN*VSFLUX%NX(1)+DKDE*EX+DKDT*TX)/VOL
      DODX = (DODN*VSFLUX%NX(1)+DODE*EX+DODT*TX)/VOL
      
      DUDY = (DUDN*VSFLUX%NX(2)+DUDE*EY+DUDT*TY)/VOL
      DVDY = (DVDN*VSFLUX%NX(2)+DVDE*EY+DVDT*TY)/VOL
      DWDY = (DWDN*VSFLUX%NX(2)+DWDE*EY+DWDT*TY)/VOL
      DTDY = (DTDN*VSFLUX%NX(2)+DTDE*EY+DTDT*TY)/VOL
      DKDY = (DKDN*VSFLUX%NX(2)+DKDE*EY+DKDT*TY)/VOL
      DODY = (DODN*VSFLUX%NX(2)+DODE*EY+DODT*TY)/VOL
      
      DUDZ = (DUDN*VSFLUX%NX(3)+DUDE*EZ+DUDT*TZ)/VOL
      DVDZ = (DVDN*VSFLUX%NX(3)+DVDE*EZ+DVDT*TZ)/VOL
      DWDZ = (DWDN*VSFLUX%NX(3)+DWDE*EZ+DWDT*TZ)/VOL
      DTDZ = (DTDN*VSFLUX%NX(3)+DTDE*EZ+DTDT*TZ)/VOL
      DKDZ = (DKDN*VSFLUX%NX(3)+DKDE*EZ+DKDT*TZ)/VOL
      DODZ = (DODN*VSFLUX%NX(3)+DODE*EZ+DODT*TZ)/VOL
      
      BIGF = VSFLUX%CALBIGF(DKDX*DODX+DKDY*DODY+DKDZ*DODZ)
      
      TDK = BIGF*VSFLUX%TDK1 + (1.D0-BIGF)*VSFLUX%TDK2
      TDO = BIGF*VSFLUX%TDO1 + (1.D0-BIGF)*VSFLUX%TDO2

      TAUXX = (VIS+EMUT)*(2.D0*DUDX -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUYY = (VIS+EMUT)*(2.D0*DVDY -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUZZ = (VIS+EMUT)*(2.D0*DWDZ -2.D0/3.D0*(DUDX+DVDY+DWDZ))
      TAUXY = (VIS+EMUT)*(DUDY+DVDX)
      TAUXZ = (VIS+EMUT)*(DUDZ+DWDX)
      TAUYZ = (VIS+EMUT)*(DVDZ+DWDY)
            
      FX(1) = 0.D0
      FX(2) = (TAUXX*VSFLUX%NX(1)+TAUXY*VSFLUX%NX(2)+TAUXZ*VSFLUX%NX(3))
      FX(3) = (TAUXY*VSFLUX%NX(1)+TAUYY*VSFLUX%NX(2)+TAUYZ*VSFLUX%NX(3))
      FX(4) = (TAUXZ*VSFLUX%NX(1)+TAUYZ*VSFLUX%NX(2)+TAUZZ*VSFLUX%NX(3))
      FX(5) = (VSFLUX%NX(1)*(UC*TAUXX+VC*TAUXY+WC*TAUXZ+(CON+TCON)*DTDX) &
            +  VSFLUX%NX(2)*(UC*TAUXY+VC*TAUYY+WC*TAUYZ+(CON+TCON)*DTDY) &
            +  VSFLUX%NX(3)*(UC*TAUXZ+VC*TAUYZ+WC*TAUZZ+(CON+TCON)*DTDZ) )
      FX(6) = 0.D0
      FX(7) = 0.D0
      FX(8) = (VIS+EMUT*TDK)*(DKDX*VSFLUX%NX(1)+DKDY*VSFLUX%NX(2)+DKDZ*VSFLUX%NX(3))
      FX(9) = (VIS+EMUT*TDO)*(DODX*VSFLUX%NX(1)+DODY*VSFLUX%NX(2)+DODZ*VSFLUX%NX(3))
      
    END SUBROUTINE VSFLUX_TURBULENT
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION KWSST(VSFLUX,PKW) RESULT(BIGF)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(IN) :: PKW
      REAL(8) :: BIGF
      REAL(8) :: TERM0,TERM1,TERM2,TERM3,CDKW,ARG1,ARG2
      REAL(8) :: RHO,YDNS,VIS,K,O
      
      RHO = 0.5D0*(VSFLUX%DVL(1)+VSFLUX%DVR(1))
      YDNS = 0.5D0*(VSFLUX%GRDL(5)+VSFLUX%GRDR(5))
      VIS = 0.5D0*(VSFLUX%TVL(1)+VSFLUX%TVR(1))
      K = 0.5D0*(VSFLUX%PV(4,8)+VSFLUX%PV(3,8)) 
      O = 0.5D0*(VSFLUX%PV(4,9)+VSFLUX%PV(3,9))
      
      TERM0 = 1.712D0*RHO/O*PKW
      CDKW = DMAX1(TERM0,1.D-10)
      
      TERM1 = DSQRT(K)/(0.09D0*O*YDNS)
      TERM2 = 500.D0*VIS/RHO/(O*YDNS**2)
      TERM3 = (3.424D0*RHO*K)/(CDKW*YDNS**2)
      
      ARG2 = DMAX1(TERM1,TERM2)
      ARG1 = DMIN1(ARG2,TERM3)
      
      BIGF = DTANH(ARG1**4)
      
    END FUNCTION KWSST
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
    FUNCTION KEPSILON(VSFLUX,PKW) RESULT(BIGF)
      IMPLICIT NONE
      CLASS(T_VSFLUX), INTENT(IN) :: VSFLUX
      REAL(8), INTENT(IN) :: PKW
      REAL(8) :: BIGF

      BIGF = 0.D0
      
    END FUNCTION KEPSILON
    !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
END MODULE VSFLUX_MODULE
    